
import { 
  Building2,
  Users,
  BarChart3,
  Database,
  Shield,
  Zap,
  Globe,
  MessageSquare,
  Calendar,
  FileText,
  CreditCard,
  Target,
  TrendingUp,
  Settings,
  Lock,
  Mail,
  Phone,
  Search,
  Filter,
  Edit,
  Save,
  Upload,
  Download,
  Share,
  Copy,
  Trash,
  Plus,
  Archive,
  Bell,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Star,
  Heart,
  ThumbsUp,
  Eye,
  Camera,
  Video,
  Image,
  Link,
  ExternalLink,
  Code,
  Terminal,
  GitBranch,
  Package,
  Truck,
  MapPin,
  Clock,
  Timer,
  Award,
  Trophy,
  Medal,
  Crown,
  Gem,
  DollarSign,
  Coins,
  Wallet,
  Receipt,
  Invoice,
  Calculator,
  PieChart,
  LineChart,
  AreaChart,
  Activity,
  Pulse,
  Workflow,
  Layers,
  Grid,
  Layout,
  Sidebar,
  Monitor,
  Smartphone,
  Tablet,
  Cloud,
  Server,
  HardDrive,
  Wifi,
  Bluetooth,
  Signal,
  Battery,
  Power,
  Plug,
  Cpu,
  MemoryStick,
  CircuitBoard,
  Briefcase,
  Handshake,
  UserCheck,
  UserPlus,
  UserMinus,
  Users2,
  Contact,
  IdCard,
  Badge,
  ShieldCheck,
  Key,
  Fingerprint,
  Scan,
  QrCode,
  Tag,
  Bookmark,
  Flag,
  Paperclip,
  Folder,
  File,
  FileSpreadsheet,
  FileBarChart,
  Clipboard,
  ClipboardList,
  NotepadText,
  PenTool,
  Brush,
  Palette,
  Lightbulb,
  Brain,
  Rocket,
  Satellite,
  Earth,
  Map,
  Navigation,
  Compass,
  Route,
  Car,
  Plane,
  Ship,
  Home,
  Store,
  ShoppingCart,
  ShoppingBag,
  Bot,
  Headphones,
  Mic,
  Speaker,
  Volume2,
  Play,
  Pause,
  SkipForward,
  FastForward,
  Repeat,
  Shuffle,
  Radio,
  Tv,
  Film,
  Music,
  Gamepad2
} from 'lucide-react';

import { ProjectTemplate } from '../projectTemplates';

export const advancedSaasTemplates: ProjectTemplate[] = [
  {
    id: 'enterprise-crm',
    name: 'CRM Empresarial Avançado',
    description: 'Sistema completo de gestão de relacionamento com cliente para empresas',
    icon: Building2,
    complexity: 'hard',
    features: [
      'Pipeline de vendas visual',
      'Automação de marketing',
      'Relatórios analíticos avançados',
      'Integração com e-mail e telefone',
      'Gestão de equipes de vendas',
      'IA para previsão de vendas',
      'API completa para integrações',
      'Dashboard executivo em tempo real'
    ]
  },
  {
    id: 'project-management-suite',
    name: 'Suite de Gestão de Projetos',
    description: 'Plataforma completa para gerenciamento ágil de projetos',
    icon: Target,
    complexity: 'hard',
    features: [
      'Metodologias Scrum e Kanban',
      'Gantt charts interativos',
      'Gestão de recursos e orçamento',
      'Time tracking automático',
      'Relatórios de produtividade',
      'Integração com Git e CI/CD',
      'Planejamento de sprints',
      'Portfolio de projetos'
    ]
  },
  {
    id: 'hr-management-platform',
    name: 'Plataforma de RH Completa',
    description: 'Sistema integrado de gestão de recursos humanos',
    icon: Users,
    complexity: 'hard',
    features: [
      'Recrutamento e seleção',
      'Onboarding automatizado',
      'Avaliação de performance',
      'Gestão de benefícios',
      'Folha de pagamento',
      'Treinamento e desenvolvimento',
      'Analytics de RH',
      'Portal do colaborador'
    ]
  },
  {
    id: 'business-intelligence',
    name: 'Business Intelligence Suite',
    description: 'Plataforma de análise e inteligência de negócios',
    icon: BarChart3,
    complexity: 'hard',
    features: [
      'Dashboards personalizáveis',
      'ETL automatizado',
      'Data warehouse integrado',
      'Machine learning integrado',
      'Relatórios automatizados',
      'Análise preditiva',
      'KPIs em tempo real',
      'Visualizações interativas'
    ]
  },
  {
    id: 'inventory-management',
    name: 'Gestão de Estoque Inteligente',
    description: 'Sistema avançado de controle de inventário',
    icon: Package,
    complexity: 'medium',
    features: [
      'Rastreamento RFID/código de barras',
      'Previsão de demanda com IA',
      'Gestão multi-localização',
      'Alertas de reposição automática',
      'Integração com fornecedores',
      'Controle de qualidade',
      'Relatórios de movimentação',
      'App mobile para warehouse'
    ]
  },
  {
    id: 'financial-erp',
    name: 'ERP Financeiro Empresarial',
    description: 'Sistema integrado de gestão financeira',
    icon: DollarSign,
    complexity: 'hard',
    features: [
      'Contabilidade automatizada',
      'Fluxo de caixa preditivo',
      'Gestão de contas a pagar/receber',
      'Conciliação bancária automática',
      'Orçamento e planejamento',
      'Compliance fiscal automatizado',
      'Análise de rentabilidade',
      'Dashboards financeiros'
    ]
  },
  {
    id: 'customer-support-platform',
    name: 'Plataforma de Suporte ao Cliente',
    description: 'Sistema omnichannel de atendimento ao cliente',
    icon: Headphones,
    complexity: 'hard',
    features: [
      'Tickets multi-canal',
      'Chat em tempo real',
      'Base de conhecimento',
      'Chatbot com IA',
      'SLA automático',
      'Análise de satisfação',
      'Integração com CRM',
      'Portal de autoatendimento'
    ]
  },
  {
    id: 'marketing-automation',
    name: 'Automação de Marketing',
    description: 'Plataforma completa de marketing digital',
    icon: Zap,
    complexity: 'hard',
    features: [
      'Email marketing automatizado',
      'Lead scoring e nurturing',
      'Campanhas multicanal',
      'A/B testing avançado',
      'Segmentação inteligente',
      'ROI tracking',
      'Social media management',
      'Landing pages builder'
    ]
  },
  {
    id: 'document-management',
    name: 'Gestão Documental Empresarial',
    description: 'Sistema de gerenciamento de documentos corporativos',
    icon: FileText,
    complexity: 'medium',
    features: [
      'Versionamento de documentos',
      'Workflow de aprovação',
      'Assinatura digital',
      'OCR e indexação automática',
      'Controle de acesso granular',
      'Auditoria completa',
      'Integração com Office 365',
      'Backup e recuperação'
    ]
  },
  {
    id: 'supply-chain-management',
    name: 'Gestão de Cadeia de Suprimentos',
    description: 'Plataforma para otimização da supply chain',
    icon: Truck,
    complexity: 'hard',
    features: [
      'Planejamento de demanda',
      'Otimização de rotas',
      'Gestão de fornecedores',
      'Rastreamento em tempo real',
      'Análise de riscos',
      'Integração IoT',
      'Sustentabilidade tracking',
      'Compliance e auditoria'
    ]
  },
  {
    id: 'cybersecurity-platform',
    name: 'Plataforma de Cibersegurança',
    description: 'Sistema completo de segurança empresarial',
    icon: Shield,
    complexity: 'hard',
    features: [
      'SIEM em tempo real',
      'Detecção de ameaças com IA',
      'Análise de vulnerabilidades',
      'Incident response automation',
      'Compliance reporting',
      'Penetration testing',
      'Security awareness training',
      'Zero trust architecture'
    ]
  },
  {
    id: 'data-analytics-platform',
    name: 'Plataforma de Analytics de Dados',
    description: 'Análise avançada de big data empresarial',
    icon: Database,
    complexity: 'hard',
    features: [
      'Data lake management',
      'Real-time streaming analytics',
      'Machine learning pipelines',
      'Self-service analytics',
      'Data governance',
      'Privacy compliance',
      'Automated insights',
      'Custom visualization engine'
    ]
  },
  {
    id: 'cloud-infrastructure',
    name: 'Gestão de Infraestrutura Cloud',
    description: 'Plataforma para gerenciar recursos cloud',
    icon: Cloud,
    complexity: 'hard',
    features: [
      'Multi-cloud management',
      'Auto-scaling inteligente',
      'Cost optimization',
      'Performance monitoring',
      'Security compliance',
      'Disaster recovery',
      'Container orchestration',
      'DevOps pipeline'
    ]
  },
  {
    id: 'api-management-platform',
    name: 'Plataforma de Gestão de APIs',
    description: 'Gateway e gerenciamento completo de APIs',
    icon: Code,
    complexity: 'hard',
    features: [
      'API gateway robusto',
      'Rate limiting e throttling',
      'Analytics de uso',
      'Developer portal',
      'Monetização de APIs',
      'Security policies',
      'Version management',
      'Mock services'
    ]
  },
  {
    id: 'workflow-automation',
    name: 'Automação de Workflows',
    description: 'Plataforma no-code para automação de processos',
    icon: Workflow,
    complexity: 'medium',
    features: [
      'Visual workflow builder',
      'Triggers e actions',
      'Integrações pré-construídas',
      'Conditional logic',
      'Error handling',
      'Monitoring e logging',
      'Template marketplace',
      'Enterprise connectors'
    ]
  },
  {
    id: 'quality-management',
    name: 'Sistema de Gestão da Qualidade',
    description: 'Plataforma para controle de qualidade empresarial',
    icon: CheckCircle,
    complexity: 'medium',
    features: [
      'Auditorias automatizadas',
      'Gestão de não-conformidades',
      'Controle de documentos',
      'Treinamentos obrigatórios',
      'Indicadores de qualidade',
      'Ações corretivas',
      'Certificações ISO',
      'Melhoria contínua'
    ]
  },
  {
    id: 'asset-management',
    name: 'Gestão de Ativos Empresariais',
    description: 'Sistema para rastreamento e manutenção de ativos',
    icon: Settings,
    complexity: 'medium',
    features: [
      'Inventário de ativos',
      'Manutenção preventiva',
      'Depreciation tracking',
      'IoT monitoring',
      'Work order management',
      'Vendor management',
      'Compliance tracking',
      'Mobile field service'
    ]
  },
  {
    id: 'enterprise-social',
    name: 'Rede Social Empresarial',
    description: 'Plataforma de colaboração e comunicação interna',
    icon: MessageSquare,
    complexity: 'medium',
    features: [
      'Feed de atividades',
      'Grupos e comunidades',
      'Knowledge sharing',
      'Video conferencing',
      'File collaboration',
      'Employee recognition',
      'Company announcements',
      'Analytics de engagement'
    ]
  },
  {
    id: 'digital-signature',
    name: 'Plataforma de Assinatura Digital',
    description: 'Sistema seguro para assinaturas eletrônicas',
    icon: PenTool,
    complexity: 'medium',
    features: [
      'Assinatura PKI',
      'Workflow de aprovação',
      'Templates de documentos',
      'Auditoria completa',
      'Compliance legal',
      'Bulk signing',
      'API para integrações',
      'Mobile signing'
    ]
  },
  {
    id: 'business-continuity',
    name: 'Gestão de Continuidade de Negócios',
    description: 'Plataforma para planejamento de continuidade',
    icon: Activity,
    complexity: 'hard',
    features: [
      'Risk assessment',
      'Business impact analysis',
      'Recovery planning',
      'Crisis communication',
      'Testing e exercises',
      'Incident management',
      'Vendor risk management',
      'Regulatory compliance'
    ]
  },
  {
    id: 'sustainability-platform',
    name: 'Plataforma de Sustentabilidade',
    description: 'Sistema para gestão ambiental e ESG',
    icon: Earth,
    complexity: 'medium',
    features: [
      'Carbon footprint tracking',
      'ESG reporting',
      'Waste management',
      'Energy optimization',
      'Supplier sustainability',
      'Compliance monitoring',
      'Goal setting e tracking',
      'Stakeholder reporting'
    ]
  },
  {
    id: 'learning-management',
    name: 'Sistema de Gestão de Aprendizagem',
    description: 'LMS empresarial para treinamento corporativo',
    icon: Brain,
    complexity: 'hard',
    features: [
      'Content authoring',
      'Adaptive learning paths',
      'Virtual classrooms',
      'Competency management',
      'Certification tracking',
      'Social learning',
      'Analytics de performance',
      'Mobile learning'
    ]
  },
  {
    id: 'revenue-optimization',
    name: 'Otimização de Revenue',
    description: 'Plataforma para maximização de receita',
    icon: TrendingUp,
    complexity: 'hard',
    features: [
      'Dynamic pricing',
      'Revenue forecasting',
      'Customer lifetime value',
      'Churn prediction',
      'Upselling automation',
      'Pricing optimization',
      'Subscription management',
      'Revenue analytics'
    ]
  },
  {
    id: 'compliance-management',
    name: 'Gestão de Compliance',
    description: 'Sistema para conformidade regulatória',
    icon: Scale,
    complexity: 'hard',
    features: [
      'Regulatory tracking',
      'Policy management',
      'Risk assessment',
      'Audit management',
      'Training compliance',
      'Incident reporting',
      'Vendor compliance',
      'Automated reporting'
    ]
  },
  {
    id: 'enterprise-search',
    name: 'Busca Empresarial Inteligente',
    description: 'Motor de busca avançado para empresas',
    icon: Search,
    complexity: 'hard',
    features: [
      'Semantic search',
      'Federated search',
      'Content discovery',
      'Search analytics',
      'Personalization',
      'Auto-suggestions',
      'Multi-language support',
      'Enterprise connectors'
    ]
  },
  {
    id: 'iot-management',
    name: 'Plataforma de Gestão IoT',
    description: 'Sistema para gerenciar dispositivos IoT',
    icon: Satellite,
    complexity: 'hard',
    features: [
      'Device management',
      'Real-time monitoring',
      'Edge computing',
      'Data visualization',
      'Predictive maintenance',
      'Security management',
      'Firmware updates',
      'Scalable architecture'
    ]
  },
  {
    id: 'blockchain-platform',
    name: 'Plataforma Blockchain Empresarial',
    description: 'Solução blockchain para negócios',
    icon: Link,
    complexity: 'hard',
    features: [
      'Smart contracts',
      'Digital identity',
      'Supply chain transparency',
      'Tokenization',
      'Consensus management',
      'Privacy controls',
      'Interoperability',
      'Enterprise security'
    ]
  },
  {
    id: 'ai-ops-platform',
    name: 'Plataforma AIOps',
    description: 'Operações de TI com inteligência artificial',
    icon: Bot,
    complexity: 'hard',
    features: [
      'Anomaly detection',
      'Root cause analysis',
      'Predictive insights',
      'Automated remediation',
      'Performance optimization',
      'Capacity planning',
      'Service mapping',
      'Intelligent alerting'
    ]
  },
  {
    id: 'digital-workplace',
    name: 'Workplace Digital',
    description: 'Ambiente de trabalho digital integrado',
    icon: Monitor,
    complexity: 'hard',
    features: [
      'Unified workspace',
      'App integrations',
      'Collaboration tools',
      'Digital assistant',
      'Workflow automation',
      'Employee analytics',
      'Virtual meetings',
      'Knowledge management'
    ]
  },
  {
    id: 'customer-data-platform',
    name: 'Plataforma de Dados do Cliente',
    description: 'CDP para unificação de dados de clientes',
    icon: Users2,
    complexity: 'hard',
    features: [
      'Identity resolution',
      'Real-time profiles',
      'Segmentation engine',
      'Journey orchestration',
      'Privacy compliance',
      'Data quality management',
      'Activation channels',
      'Analytics e insights'
    ]
  }
];
