
import { 
  ShoppingCart, 
  Store, 
  Package, 
  CreditCard, 
  BarChart3, 
  Users, 
  Briefcase, 
  Building, 
  Truck, 
  MapPin, 
  Phone,
  Calculator,
  Globe,
  Brain,
  Code,
  Settings,
  Zap,
  Activity,
  Shield,
  CheckCircle,
  FileText,
  Calendar,
  MessageSquare,
  Timer,
  Target,
  TrendingUp,
  DollarSign,
  PieChart,
  Layers,
  Database,
  Cloud,
  Lock,
  Key,
  Mail,
  Bell,
  Search,
  Filter,
  Edit,
  Upload,
  Download,
  Share,
  Copy,
  Trash,
  Plus,
  Minus,
  Star,
  Heart,
  ThumbsUp,
  Eye,
  Camera,
  Video,
  Image,
  Link,
  ExternalLink,
  Home,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Maximize,
  Minimize,
  RotateCcw,
  RefreshCw,
  Save,
  Bookmark,
  Flag,
  Award,
  Medal,
  Trophy,
  Crown,
  Gem,
  Coins,
  Banknote,
  Wallet,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,
  Server,
  HardDrive,
  Cpu,
  MemoryStick,
  Wifi,
  Bluetooth,
  Usb,
  Battery,
  Power,
  Plug,
  Cable,
  Router,
  Antenna,
  Signal,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Rewind,
  FastForward,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Headphones,
  Mic,
  MicOff,
  Speaker,
  Radio,
  Disc,
  Music,
  Film,
  Tv,
  Theater,
  Gamepad2,
  Joystick,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Puzzle,
  Crosshair,
  Radar,
  Compass,
  Navigation,
  Map,
  Route,
  Car,
  Bus,
  Train,
  Plane,
  Bike,
  Ship,
  Rocket,
  Ambulance,
  TrendingDown,
  BarChart,
  LineChart,
  AreaChart,
  ScatterChart,
  Inbox,
  Send,
  Reply,
  ReplyAll,
  Forward,
  Archive,
  Trash2,
  MailOpen,
  MailCheck,
  AtSign,
  Hash,
  Percent,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  List,
  ListOrdered,
  Quote,
  Code2,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  Folder,
  FolderOpen,
  File,
  FileEdit,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileSpreadsheet,
  FileBarChart,
  FileLineChart,
  ClipboardList,
  Clipboard,
  ClipboardCheck,
  ClipboardX,
  ClipboardCopy,
  Scissors,
  PaintBucket,
  Palette,
  Brush,
  Pen,
  PenTool,
  Highlighter,
  Eraser,
  Ruler,
  Move,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Pentagon,
  Octagon,
  Diamond,
  RectangleHorizontal,
  RectangleVertical,
  Shapes,
  Grid,
  Layout,
  Sidebar,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  SplitSquareHorizontal,
  SplitSquareVertical,
  Columns,
  Rows,
  Table,
  Clock,
  Watch,
  Hourglass,
  Sunrise,
  Sunset,
  Sun,
  Moon,
  Stars,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Umbrella,
  Rainbow,
  Snowflake,
  Thermometer,
  Wind,
  Mountain,
  TreePine,
  Trees,
  Flower,
  Flower2,
  Sprout,
  Leaf,
  Bug,
  Fish,
  Bird,
  Rabbit,
  Squirrel,
  Dog,
  Cat,
  Egg,
  Bone,
  Footprints,
  Apple,
  Cherry,
  Grape,
  Banana,
  Carrot,
  Pizza,
  Sandwich,
  Cookie,
  Cake,
  IceCream,
  Coffee,
  Beer,
  Wine,
  Martini,
  Soup,
  Salad,
  ChefHat,
  UtensilsCrossed,
  Baby,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UsersRound,
  UserRound,
  UserSquare,
  UserCircle,
  Contact,
  IdCard,
  Badge,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  ShieldBan,
  Fingerprint,
  Scan,
  QrCode,
  Barcode,
  Tag,
  Tags,
  NotepadText,
  StickyNote,
  Paperclip,
  Abacus,
  Microscope,
  Telescope,
  Magnet,
  Atom,
  Dna,
  Pill,
  Syringe,
  Bandage,
  Stethoscope,
  HeartPulse,
  Lightbulb,
  Flashlight,
  Flame,
  Earth,
  Satellite,
  Scale,
  Wrench,
  Factory,
  Warehouse,
  Package2,
  ShoppingBag,
  Receipt,
  TrendingDown as Decline,
  Bot,
  Handshake,
  BookOpen,
  GraduationCap,
  Presentation,
  UserCog,
  Gavel,
  BarChart4,
  Database as Db,
  MousePointer,
  Keyboard,
  Printer,
  Scanner,
  Webcam,
  Cog,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Volume1,
  RefreshCcw,
  History,
  HelpCircle,
  Info
} from 'lucide-react';

import { ProjectTemplate } from '../projectTemplates';

export const businessTemplates: ProjectTemplate[] = [
  {
    id: 'ecommerce',
    name: 'E-commerce Platform',
    description: 'Plataforma completa de comércio eletrônico com carrinho, pagamentos e gestão de produtos',
    icon: ShoppingCart,
    complexity: 'medium',
    features: [
      'Catálogo de produtos',
      'Carrinho de compras',
      'Sistema de pagamento',
      'Painel administrativo',
      'Gestão de pedidos',
      'Sistema de avaliações'
    ]
  },
  {
    id: 'marketplace',
    name: 'Marketplace Multi-vendor',
    description: 'Marketplace para múltiplos vendedores com comissões e gestão centralizada',
    icon: Store,
    complexity: 'hard',
    features: [
      'Multi-vendedores',
      'Sistema de comissões',
      'Gestão de produtos',
      'Painel do vendedor',
      'Sistema de disputas',
      'Analytics avançado'
    ]
  },
  {
    id: 'inventory',
    name: 'Sistema de Inventário',
    description: 'Controle completo de estoque com código de barras e relatórios',
    icon: Package,
    complexity: 'medium',
    features: [
      'Controle de estoque',
      'Código de barras',
      'Relatórios detalhados',
      'Alertas de estoque baixo',
      'Gestão de fornecedores',
      'Histórico de movimentações'
    ]
  },
  {
    id: 'pos-system',
    name: 'Sistema PDV',
    description: 'Point of Sale completo para lojas físicas',
    icon: CreditCard,
    complexity: 'medium',
    features: [
      'Vendas rápidas',
      'Múltiplas formas de pagamento',
      'Impressão de cupons',
      'Controle de caixa',
      'Relatórios de vendas',
      'Gestão de funcionários'
    ]
  },
  {
    id: 'analytics-dashboard',
    name: 'Dashboard Analytics',
    description: 'Painel de análise de dados em tempo real',
    icon: BarChart3,
    complexity: 'medium',
    features: [
      'Visualização de dados',
      'Relatórios customizáveis',
      'Métricas em tempo real',
      'Exportação de dados',
      'Alerts automáticos',
      'Integração com APIs'
    ]
  },
  {
    id: 'crm-system',
    name: 'Sistema CRM',
    description: 'Gestão completa de relacionamento com clientes',
    icon: Users,
    complexity: 'hard',
    features: [
      'Gestão de leads',
      'Pipeline de vendas',
      'Histórico de interações',
      'Automação de marketing',
      'Relatórios de performance',
      'Integração com email'
    ]
  },
  {
    id: 'booking-system',
    name: 'Sistema de Agendamento',
    description: 'Plataforma de agendamento online para serviços',
    icon: Calendar,
    complexity: 'medium',
    features: [
      'Calendário interativo',
      'Gestão de horários',
      'Notificações automáticas',
      'Pagamento online',
      'Gestão de clientes',
      'Relatórios de ocupação'
    ]
  },
  {
    id: 'invoice-generator',
    name: 'Gerador de Faturas',
    description: 'Sistema completo para criação e gestão de faturas',
    icon: FileText,
    complexity: 'easy',
    features: [
      'Criação de faturas',
      'Templates customizáveis',
      'Controle de pagamentos',
      'Relatórios financeiros',
      'Envio por email',
      'Gestão de clientes'
    ]
  },
  {
    id: 'chat-support',
    name: 'Chat de Suporte',
    description: 'Sistema de chat em tempo real para atendimento ao cliente',
    icon: MessageSquare,
    complexity: 'medium',
    features: [
      'Chat em tempo real',
      'Sistema de tickets',
      'Histórico de conversas',
      'Múltiplos operadores',
      'Notificações push',
      'Integração com CRM'
    ]
  },
  {
    id: 'donation-platform',
    name: 'Plataforma de Doações',
    description: 'Sistema para campanhas de arrecadação e doações online',
    icon: Heart,
    complexity: 'medium',
    features: [
      'Campanhas de doação',
      'Processamento de pagamentos',
      'Metas e progresso',
      'Certificados de doação',
      'Compartilhamento social',
      'Relatórios de arrecadação'
    ]
  },
  {
    id: 'freelancer-platform',
    name: 'Plataforma Freelancer',
    description: 'Marketplace para freelancers e clientes se conectarem',
    icon: Briefcase,
    complexity: 'hard',
    features: [
      'Perfis de freelancers',
      'Sistema de propostas',
      'Escrow de pagamentos',
      'Avaliações e reviews',
      'Chat integrado',
      'Gestão de projetos'
    ]
  },
  {
    id: 'real-estate',
    name: 'Imobiliária Online',
    description: 'Plataforma para listagem e venda de imóveis',
    icon: Building,
    complexity: 'medium',
    features: [
      'Listagem de imóveis',
      'Busca avançada',
      'Galeria de fotos',
      'Tour virtual',
      'Agendamento de visitas',
      'Calculadora de financiamento'
    ]
  },
  {
    id: 'delivery-app',
    name: 'App de Delivery',
    description: 'Aplicativo completo de delivery com rastreamento',
    icon: Truck,
    complexity: 'hard',
    features: [
      'Pedidos online',
      'Rastreamento em tempo real',
      'Múltiplos restaurantes',
      'Sistema de avaliação',
      'Cupons de desconto',
      'Gestão de entregadores'
    ]
  },
  {
    id: 'location-finder',
    name: 'Localizador de Serviços',
    description: 'Encontre serviços próximos com geolocalização',
    icon: MapPin,
    complexity: 'medium',
    features: [
      'Geolocalização',
      'Busca por proximidade',
      'Avaliações de usuários',
      'Informações de contato',
      'Rotas e direções',
      'Filtros avançados'
    ]
  },
  {
    id: 'voip-system',
    name: 'Sistema VoIP',
    description: 'Sistema de telefonia pela internet para empresas',
    icon: Phone,
    complexity: 'hard',
    features: [
      'Chamadas VoIP',
      'Central telefônica',
      'Gravação de chamadas',
      'Relatórios de uso',
      'Múltiplas linhas',
      'Integração com CRM'
    ]
  },
  {
    id: 'ai-chatbot',
    name: 'Chatbot com IA',
    description: 'Assistente virtual inteligente para atendimento',
    icon: Bot,
    complexity: 'hard',
    features: [
      'Processamento de linguagem natural',
      'Respostas inteligentes',
      'Integração com sistemas',
      'Aprendizado contínuo',
      'Múltiplos canais',
      'Analytics de conversas'
    ]
  },
  {
    id: 'project-management',
    name: 'Gestão de Projetos',
    description: 'Ferramenta completa para gerenciamento de projetos',
    icon: Target,
    complexity: 'hard',
    features: [
      'Cronograma de tarefas',
      'Gráfico de Gantt',
      'Gestão de equipes',
      'Controle de tempo',
      'Relatórios de progresso',
      'Integração com calendário'
    ]
  },
  {
    id: 'social-network',
    name: 'Rede Social',
    description: 'Plataforma de rede social com recursos modernos',
    icon: Users,
    complexity: 'hard',
    features: [
      'Feed de notícias',
      'Sistema de amizades',
      'Mensagens privadas',
      'Grupos e comunidades',
      'Compartilhamento de mídia',
      'Sistema de notificações'
    ]
  },
  {
    id: 'learning-platform',
    name: 'Plataforma de Ensino',
    description: 'Sistema completo para cursos online',
    icon: Brain,
    complexity: 'hard',
    features: [
      'Criação de cursos',
      'Vídeo aulas',
      'Exercícios interativos',
      'Certificados',
      'Progresso do aluno',
      'Fórum de discussão'
    ]
  },
  {
    id: 'hr-management',
    name: 'Sistema de RH',
    description: 'Gestão completa de recursos humanos',
    icon: UserCog,
    complexity: 'hard',
    features: [
      'Controle de ponto',
      'Folha de pagamento',
      'Avaliação de desempenho',
      'Banco de talentos',
      'Gestão de benefícios',
      'Portal do funcionário'
    ]
  },
  {
    id: 'supply-chain',
    name: 'Cadeia de Suprimentos',
    description: 'Gestão completa da cadeia de suprimentos',
    icon: Truck,
    complexity: 'hard',
    features: [
      'Rastreamento de produtos',
      'Gestão de fornecedores',
      'Otimização de rotas',
      'Controle de qualidade',
      'Analytics de desempenho',
      'Previsão de demanda'
    ]
  },
  {
    id: 'manufacturing-erp',
    name: 'ERP Industrial',
    description: 'Sistema ERP para indústrias manufatureiras',
    icon: Factory,
    complexity: 'hard',
    features: [
      'Planejamento de produção',
      'Controle de qualidade',
      'Gestão de recursos',
      'Manutenção preventiva',
      'Custos de produção',
      'Rastreabilidade completa'
    ]
  },
  {
    id: 'warehouse-management',
    name: 'Gestão de Armazém',
    description: 'Sistema WMS para otimização de armazéns',
    icon: Warehouse,
    complexity: 'hard',
    features: [
      'Localização inteligente',
      'Picking otimizado',
      'Controle de entrada/saída',
      'Inventário cíclico',
      'Integração com transportadoras',
      'Analytics de produtividade'
    ]
  },
  {
    id: 'procurement-system',
    name: 'Sistema de Compras',
    description: 'Plataforma para gestão de compras corporativas',
    icon: ShoppingBag,
    complexity: 'medium',
    features: [
      'Catálogo de produtos',
      'Fluxo de aprovação',
      'Comparação de preços',
      'Gestão de contratos',
      'Avaliação de fornecedores',
      'Relatórios de gastos'
    ]
  },
  {
    id: 'expense-management',
    name: 'Gestão de Despesas',
    description: 'Sistema para controle de despesas corporativas',
    icon: Receipt,
    complexity: 'medium',
    features: [
      'Captura de recibos',
      'Aprovação automática',
      'Reembolso rápido',
      'Integração contábil',
      'Políticas personalizadas',
      'Analytics de gastos'
    ]
  },
  {
    id: 'fleet-management',
    name: 'Gestão de Frota',
    description: 'Sistema completo para gestão de frotas',
    icon: Car,
    complexity: 'hard',
    features: [
      'Rastreamento GPS',
      'Controle de combustível',
      'Manutenção preventiva',
      'Gestão de motoristas',
      'Otimização de rotas',
      'Relatórios de performance'
    ]
  },
  {
    id: 'asset-management',
    name: 'Gestão de Ativos',
    description: 'Controle patrimonial e gestão de ativos',
    icon: Package2,
    complexity: 'medium',
    features: [
      'Cadastro de ativos',
      'Depreciação automática',
      'Manutenção programada',
      'Localização de ativos',
      'Histórico completo',
      'Relatórios fiscais'
    ]
  },
  {
    id: 'business-intelligence',
    name: 'Business Intelligence',
    description: 'Plataforma de inteligência de negócios',
    icon: BarChart4,
    complexity: 'hard',
    features: [
      'Dashboards interativos',
      'Data mining',
      'Análise preditiva',
      'KPIs em tempo real',
      'Relatórios automáticos',
      'Visualização avançada'
    ]
  },
  {
    id: 'compliance-management',
    name: 'Gestão de Compliance',
    description: 'Sistema para gestão de conformidade regulatória',
    icon: Shield,
    complexity: 'hard',
    features: [
      'Monitoramento regulatório',
      'Auditorias internas',
      'Gestão de riscos',
      'Treinamento compliance',
      'Relatórios regulatórios',
      'Alertas automáticos'
    ]
  },
  {
    id: 'contract-management',
    name: 'Gestão de Contratos',
    description: 'Sistema para gerenciamento de contratos',
    icon: FileText,
    complexity: 'medium',
    features: [
      'Biblioteca de contratos',
      'Assinatura digital',
      'Renovação automática',
      'Alertas de vencimento',
      'Templates padronizados',
      'Histórico de alterações'
    ]
  },
  {
    id: 'legal-case-management',
    name: 'Gestão Jurídica',
    description: 'Sistema para escritórios de advocacia',
    icon: Gavel,
    complexity: 'hard',
    features: [
      'Gestão de processos',
      'Controle de prazos',
      'Agenda de audiências',
      'Biblioteca jurídica',
      'Controle financeiro',
      'Portal do cliente'
    ]
  },
  {
    id: 'quality-management',
    name: 'Gestão da Qualidade',
    description: 'Sistema QMS para controle de qualidade',
    icon: Award,
    complexity: 'hard',
    features: [
      'Controle de processos',
      'Não conformidades',
      'Ações corretivas',
      'Auditorias internas',
      'Certificações ISO',
      'Melhoria contínua'
    ]
  },
  {
    id: 'vendor-management',
    name: 'Gestão de Fornecedores',
    description: 'Sistema para avaliação e gestão de fornecedores',
    icon: Handshake,
    complexity: 'medium',
    features: [
      'Cadastro de fornecedores',
      'Avaliação de performance',
      'Qualificação automática',
      'Portal do fornecedor',
      'Gestão de SLAs',
      'Analytics de compras'
    ]
  },
  {
    id: 'training-management',
    name: 'Gestão de Treinamentos',
    description: 'Plataforma para treinamentos corporativos',
    icon: GraduationCap,
    complexity: 'medium',
    features: [
      'Catálogo de cursos',
      'Trilhas de aprendizado',
      'Avaliações online',
      'Certificações',
      'Plano de desenvolvimento',
      'Relatórios de progresso'
    ]
  },
  {
    id: 'safety-management',
    name: 'Gestão de Segurança',
    description: 'Sistema para gestão de segurança do trabalho',
    icon: Shield,
    complexity: 'medium',
    features: [
      'Registro de acidentes',
      'Análise de riscos',
      'Treinamentos de segurança',
      'Inspeções programadas',
      'EPIs e equipamentos',
      'Indicadores de segurança'
    ]
  },
  {
    id: 'energy-management',
    name: 'Gestão de Energia',
    description: 'Sistema para monitoramento e otimização energética',
    icon: Zap,
    complexity: 'hard',
    features: [
      'Monitoramento em tempo real',
      'Análise de consumo',
      'Detecção de desperdício',
      'Otimização automática',
      'Relatórios de eficiência',
      'Previsão de custos'
    ]
  },
  {
    id: 'maintenance-management',
    name: 'Gestão de Manutenção',
    description: 'Sistema CMMS para manutenção industrial',
    icon: Wrench,
    complexity: 'hard',
    features: [
      'Ordens de serviço',
      'Manutenção preventiva',
      'Controle de peças',
      'Histórico de equipamentos',
      'Planejamento de paradas',
      'KPIs de manutenção'
    ]
  },
  {
    id: 'carbon-tracker',
    name: 'Rastreador de Pegada de Carbono',
    description: 'Monitor de sustentabilidade empresarial',
    icon: Leaf,
    complexity: 'medium',
    features: [
      'Cálculo de pegada de carbono',
      'Metas de sustentabilidade',
      'Relatórios ESG',
      'Offset de carbono',
      'Certificações verdes',
      'Dashboard ambiental'
    ]
  },
  {
    id: 'knowledge-management',
    name: 'Gestão do Conhecimento',
    description: 'Base de conhecimento corporativa',
    icon: BookOpen,
    complexity: 'medium',
    features: [
      'Base de conhecimento',
      'Wiki corporativa',
      'Busca inteligente',
      'Versionamento de documentos',
      'Colaboração em equipe',
      'Analytics de uso'
    ]
  },
  {
    id: 'presentation-platform',
    name: 'Plataforma de Apresentações',
    description: 'Sistema para criação e gestão de apresentações',
    icon: Presentation,
    complexity: 'medium',
    features: [
      'Editor de apresentações',
      'Templates corporativos',
      'Colaboração em tempo real',
      'Biblioteca de mídia',
      'Apresentação remota',
      'Analytics de engajamento'
    ]
  },
  {
    id: 'document-automation',
    name: 'Automação de Documentos',
    description: 'Sistema para automação de criação de documentos',
    icon: FileText,
    complexity: 'hard',
    features: [
      'Templates inteligentes',
      'Preenchimento automático',
      'Fluxo de aprovação',
      'Assinatura eletrônica',
      'Versionamento',
      'Integração com sistemas'
    ]
  }
];
