
import { 
  ShoppingCart, 
  Store, 
  Package, 
  CreditCard, 
  BarChart3, 
  Users, 
  Briefcase, 
  Building, 
  Truck, 
  MapPin, 
  Phone,
  Calculator,
  Globe,
  Brain,
  Code,
  Settings,
  Zap,
  Bot,
  Activity,
  Shield,
  CheckCircle,
  FileText,
  Calendar,
  MessageSquare,
  Timer,
  Target,
  TrendingUp,
  DollarSign,
  PieChart,
  Layers,
  Database,
  Cloud,
  Lock,
  Key,
  Mail,
  Bell,
  Search,
  Filter,
  Edit,
  Upload,
  Download,
  Share,
  Copy,
  Trash,
  Plus,
  Minus,
  Star,
  Heart,
  ThumbsUp,
  Eye,
  Camera,
  Video,
  Image,
  Link,
  ExternalLink,
  Home,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Maximize,
  Minimize,
  RotateCcw,
  RefreshCw,
  Save,
  Bookmark,
  Flag,
  Award,
  Medal,
  Trophy,
  Crown,
  Gem,
  Coins,
  Banknote,
  Wallet,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,
  Server,
  HardDrive,
  Cpu,
  MemoryStick,
  Wifi,
  Bluetooth,
  Usb,
  Battery,
  Power,
  Plug,
  Cable,
  Router,
  Antenna,
  Signal,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Stop,
  Rewind,
  FastForward,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Headphones,
  Mic,
  MicOff,
  Speaker,
  Radio,
  Disc,
  Music,
  Film,
  Tv,
  Theater,
  Gamepad2,
  Joystick,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Puzzle,
  Crosshair,
  Radar,
  Compass,
  Navigation,
  Map,
  Route,
  Car,
  Bus,
  Train,
  Plane,
  Bike,
  Ship,
  Rocket,
  Helicopter,
  Ambulance,
  Taxi,
  TrendingDown,
  BarChart,
  LineChart,
  AreaChart,
  ScatterChart,
  Inbox,
  Send,
  Reply,
  ReplyAll,
  Forward,
  Archive,
  Trash2,
  Spam,
  MailOpen,
  MailCheck,
  AtSign,
  Hash,
  Percent,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  List,
  ListOrdered,
  Quote,
  Code2,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  Folder,
  FolderOpen,
  File,
  FileEdit,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileSpreadsheet,
  FileBarChart,
  FileLineChart,
  ClipboardList,
  Clipboard,
  ClipboardCheck,
  ClipboardX,
  ClipboardCopy,
  Scissors,
  PaintBucket,
  Palette,
  Brush,
  Pen,
  PenTool,
  Highlighter,
  Eraser,
  Ruler,
  Move,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Pentagon,
  Octagon,
  Diamond,
  RectangleHorizontal,
  RectangleVertical,
  Shapes,
  Grid,
  Layout,
  Sidebar,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  SplitSquareHorizontal,
  SplitSquareVertical,
  Columns,
  Rows,
  Table,
  Clock,
  Watch,
  Stopwatch,
  Hourglass,
  Sunrise,
  Sunset,
  Sun,
  Moon,
  Stars,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Umbrella,
  Rainbow,
  Snowflake,
  Thermometer,
  Wind,
  Tornado,
  Volcano,
  Mountain,
  TreePine,
  Trees,
  Flower,
  Flower2,
  Sprout,
  Leaf,
  Bug,
  Fish,
  Bird,
  Rabbit,
  Squirrel,
  Dog,
  Cat,
  Horse,
  Cow,
  Pig,
  Sheep,
  Chicken,
  Egg,
  Bone,
  Footprints,
  Paw,
  Apple,
  Cherry,
  Grape,
  Orange,
  Banana,
  Strawberry,
  Carrot,
  Corn,
  Pizza,
  Sandwich,
  Cookie,
  Cake,
  IceCream,
  Coffee,
  Tea,
  Beer,
  Wine,
  Martini,
  Soup,
  Salad,
  ChefHat,
  UtensilsCrossed,
  Fork,
  Spoon,
  Knife,
  Plate,
  Glass,
  Bottle,
  Can,
  Baby,
  Child,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UsersRound,
  UserRound,
  UserSquare,
  UserCircle,
  Contact,
  Contacts,
  AddressBook,
  IdCard,
  Badge,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  ShieldBan,
  Fingerprint,
  Scan,
  QrCode,
  Barcode,
  Tag,
  Tags,
  NotepadText,
  StickyNote,
  Pushpin,
  Paperclip,
  Stapler,
  Abacus,
  Protractor,
  Microscope,
  Telescope,
  Magnet,
  Atom,
  Dna,
  Pill,
  Syringe,
  Bandage,
  Stethoscope,
  XRay,
  Pulse,
  HeartPulse,
  Lightbulb,
  Flashlight,
  Candle,
  Fire,
  Flame,
  Spark,
  Comet,
  Planet,
  Earth,
  Satellite,
  Ufo,
  Alien,
  Bot
} from 'lucide-react';

import { ProjectTemplate } from '../projectTemplates';

export const businessTemplates: ProjectTemplate[] = [
  {
    id: 'ecommerce',
    name: 'E-commerce Platform',
    description: 'Plataforma completa de comércio eletrônico com carrinho, pagamentos e gestão de produtos',
    icon: ShoppingCart,
    complexity: 'medium',
    features: [
      'Catálogo de produtos',
      'Carrinho de compras',
      'Sistema de pagamento',
      'Painel administrativo',
      'Gestão de pedidos',
      'Sistema de avaliações'
    ]
  },
  {
    id: 'marketplace',
    name: 'Marketplace Multi-vendor',
    description: 'Marketplace para múltiplos vendedores com comissões e gestão centralizada',
    icon: Store,
    complexity: 'hard',
    features: [
      'Multi-vendedores',
      'Sistema de comissões',
      'Gestão de produtos',
      'Painel do vendedor',
      'Sistema de disputas',
      'Analytics avançado'
    ]
  },
  {
    id: 'inventory',
    name: 'Sistema de Inventário',
    description: 'Controle completo de estoque com código de barras e relatórios',
    icon: Package,
    complexity: 'medium',
    features: [
      'Controle de estoque',
      'Código de barras',
      'Relatórios detalhados',
      'Alertas de estoque baixo',
      'Gestão de fornecedores',
      'Histórico de movimentações'
    ]
  },
  {
    id: 'pos-system',
    name: 'Sistema PDV',
    description: 'Point of Sale completo para lojas físicas',
    icon: CreditCard,
    complexity: 'medium',
    features: [
      'Vendas rápidas',
      'Múltiplas formas de pagamento',
      'Impressão de cupons',
      'Controle de caixa',
      'Relatórios de vendas',
      'Gestão de funcionários'
    ]
  },
  {
    id: 'analytics-dashboard',
    name: 'Dashboard Analytics',
    description: 'Painel de análise de dados em tempo real',
    icon: BarChart3,
    complexity: 'medium',
    features: [
      'Visualização de dados',
      'Relatórios customizáveis',
      'Métricas em tempo real',
      'Exportação de dados',
      'Alerts automáticos',
      'Integração com APIs'
    ]
  },
  {
    id: 'crm-system',
    name: 'Sistema CRM',
    description: 'Gestão completa de relacionamento com clientes',
    icon: Users,
    complexity: 'hard',
    features: [
      'Gestão de leads',
      'Pipeline de vendas',
      'Histórico de interações',
      'Automação de marketing',
      'Relatórios de performance',
      'Integração com email'
    ]
  },
  {
    id: 'booking-system',
    name: 'Sistema de Agendamento',
    description: 'Plataforma de agendamento online para serviços',
    icon: Calendar,
    complexity: 'medium',
    features: [
      'Calendário interativo',
      'Gestão de horários',
      'Notificações automáticas',
      'Pagamento online',
      'Gestão de clientes',
      'Relatórios de ocupação'
    ]
  },
  {
    id: 'invoice-generator',
    name: 'Gerador de Faturas',
    description: 'Sistema completo para criação e gestão de faturas',
    icon: FileText,
    complexity: 'easy',
    features: [
      'Criação de faturas',
      'Templates customizáveis',
      'Controle de pagamentos',
      'Relatórios financeiros',
      'Envio por email',
      'Gestão de clientes'
    ]
  },
  {
    id: 'chat-support',
    name: 'Chat de Suporte',
    description: 'Sistema de chat em tempo real para atendimento ao cliente',
    icon: MessageSquare,
    complexity: 'medium',
    features: [
      'Chat em tempo real',
      'Sistema de tickets',
      'Histórico de conversas',
      'Múltiplos operadores',
      'Notificações push',
      'Integração com CRM'
    ]
  },
  {
    id: 'donation-platform',
    name: 'Plataforma de Doações',
    description: 'Sistema para campanhas de arrecadação e doações online',
    icon: Heart,
    complexity: 'medium',
    features: [
      'Campanhas de doação',
      'Processamento de pagamentos',
      'Metas e progresso',
      'Certificados de doação',
      'Compartilhamento social',
      'Relatórios de arrecadação'
    ]
  },
  {
    id: 'freelancer-platform',
    name: 'Plataforma Freelancer',
    description: 'Marketplace para freelancers e clientes se conectarem',
    icon: Briefcase,
    complexity: 'hard',
    features: [
      'Perfis de freelancers',
      'Sistema de propostas',
      'Escrow de pagamentos',
      'Avaliações e reviews',
      'Chat integrado',
      'Gestão de projetos'
    ]
  },
  {
    id: 'real-estate',
    name: 'Imobiliária Online',
    description: 'Plataforma para listagem e venda de imóveis',
    icon: Building,
    complexity: 'medium',
    features: [
      'Listagem de imóveis',
      'Busca avançada',
      'Galeria de fotos',
      'Tour virtual',
      'Agendamento de visitas',
      'Calculadora de financiamento'
    ]
  },
  {
    id: 'delivery-app',
    name: 'App de Delivery',
    description: 'Aplicativo completo de delivery com rastreamento',
    icon: Truck,
    complexity: 'hard',
    features: [
      'Pedidos online',
      'Rastreamento em tempo real',
      'Múltiplos restaurantes',
      'Sistema de avaliação',
      'Cupons de desconto',
      'Gestão de entregadores'
    ]
  },
  {
    id: 'location-finder',
    name: 'Localizador de Serviços',
    description: 'Encontre serviços próximos com geolocalização',
    icon: MapPin,
    complexity: 'medium',
    features: [
      'Geolocalização',
      'Busca por proximidade',
      'Avaliações de usuários',
      'Informações de contato',
      'Rotas e direções',
      'Filtros avançados'
    ]
  },
  {
    id: 'voip-system',
    name: 'Sistema VoIP',
    description: 'Sistema de telefonia pela internet para empresas',
    icon: Phone,
    complexity: 'hard',
    features: [
      'Chamadas VoIP',
      'Central telefônica',
      'Gravação de chamadas',
      'Relatórios de uso',
      'Múltiplas linhas',
      'Integração com CRM'
    ]
  },
  {
    id: 'influencer-platform',
    name: 'Plataforma de Influenciadores',
    description: 'Conecte marcas com influenciadores digitais',
    icon: Users,
    complexity: 'hard',
    features: [
      'Perfis de influenciadores',
      'Métricas de engajamento',
      'Sistema de propostas',
      'Gestão de campanhas',
      'Pagamentos automáticos',
      'Analytics de performance'
    ]
  },
  {
    id: 'virtual-coworking',
    name: 'Coworking Virtual',
    description: 'Espaço de trabalho colaborativo online',
    icon: Users,
    complexity: 'hard',
    features: [
      'Salas virtuais',
      'Reserva de espaços',
      'Networking entre membros',
      'Eventos online',
      'Sistema de pontos',
      'Dashboard de produtividade'
    ]
  },
  {
    id: 'subscription-box',
    name: 'Box de Assinatura',
    description: 'Plataforma para serviços de box mensais',
    icon: Package,
    complexity: 'hard',
    features: [
      'Múltiplos tipos de box',
      'Customização de produtos',
      'Gestão de assinantes',
      'Logística automatizada',
      'Feedback de produtos',
      'Programa de fidelidade'
    ]
  },
  {
    id: 'peer-to-peer-marketplace',
    name: 'Marketplace P2P',
    description: 'Marketplace pessoa-a-pessoa seguro',
    icon: Users,
    complexity: 'hard',
    features: [
      'Verificação de identidade',
      'Sistema de avaliações',
      'Pagamento escrow',
      'Chat integrado',
      'Resolução de disputas',
      'Geolocalização'
    ]
  },
  {
    id: 'virtual-events-platform',
    name: 'Plataforma de Eventos Virtuais',
    description: 'Organize eventos online profissionais',
    icon: Video,
    complexity: 'hard',
    features: [
      'Transmissão ao vivo',
      'Salas de breakout',
      'Networking virtual',
      'Stands de exposição',
      'Sistema de tickets',
      'Analytics de participação'
    ]
  },
  {
    id: 'carbon-offset-marketplace',
    name: 'Marketplace de Créditos de Carbono',
    description: 'Compra e venda de créditos de carbono',
    icon: Leaf,
    complexity: 'hard',
    features: [
      'Marketplace de créditos',
      'Verificação de projetos',
      'Calculadora de pegada',
      'Certificação blockchain',
      'Relatórios de impacto',
      'Portfolio verde'
    ]
  },
  {
    id: 'fleet-management',
    name: 'Gestão de Frota',
    description: 'Sistema completo para gestão de frotas',
    icon: Truck,
    complexity: 'hard',
    features: [
      'Rastreamento GPS',
      'Manutenção preventiva',
      'Gestão de combustível',
      'Roteirização inteligente',
      'Relatórios de performance',
      'Alertas automáticos'
    ]
  },
  {
    id: 'smart-contracts-platform',
    name: 'Plataforma de Smart Contracts',
    description: 'Criação e gestão de contratos inteligentes',
    icon: FileText,
    complexity: 'hard',
    features: [
      'Editor de contratos',
      'Deploy automático',
      'Auditoria de código',
      'Multi-blockchain',
      'Templates legais',
      'Execução automática'
    ]
  },
  {
    id: 'virtual-reality-showroom',
    name: 'Showroom em Realidade Virtual',
    description: 'Experiências imersivas para vendas',
    icon: Eye,
    complexity: 'hard',
    features: [
      'Ambientes 3D',
      'Interação em VR',
      'Produtos configuráveis',
      'Tour guiado',
      'Analytics de comportamento',
      'Integração com e-commerce'
    ]
  },
  {
    id: 'microlearning-platform',
    name: 'Plataforma de Microlearning',
    description: 'Aprendizado corporativo em pequenas doses',
    icon: GraduationCap,
    complexity: 'medium',
    features: [
      'Conteúdo bite-sized',
      'Gamificação',
      'Adaptive learning',
      'Mobile-first',
      'Analytics de engajamento',
      'Certificações micro'
    ]
  },
  {
    id: 'ai-customer-service',
    name: 'Atendimento com IA',
    description: 'Chatbots inteligentes para atendimento',
    icon: Bot,
    complexity: 'hard',
    features: [
      'Chatbot com IA',
      'Processamento de linguagem natural',
      'Escalação inteligente',
      'Base de conhecimento',
      'Analytics de conversas',
      'Múltiplos canais'
    ]
  },
  {
    id: 'blockchain-voting',
    name: 'Votação Blockchain',
    description: 'Sistema de votação transparente e seguro',
    icon: Vote,
    complexity: 'hard',
    features: [
      'Votação descentralizada',
      'Verificação de identidade',
      'Transparência total',
      'Imutabilidade',
      'Auditoria pública',
      'Múltiplos tipos de eleição'
    ]
  },
  {
    id: 'iot-dashboard',
    name: 'Dashboard IoT',
    description: 'Central de controle para dispositivos IoT',
    icon: Wifi,
    complexity: 'hard',
    features: [
      'Gestão de dispositivos',
      'Monitoramento em tempo real',
      'Automação de regras',
      'Alertas inteligentes',
      'Análise de dados',
      'Controle remoto'
    ]
  },
  {
    id: 'virtual-assistant-platform',
    name: 'Plataforma de Assistente Virtual',
    description: 'Assistentes virtuais personalizáveis',
    icon: MessageSquare,
    complexity: 'hard',
    features: [
      'IA conversacional',
      'Integração com sistemas',
      'Personalização de persona',
      'Múltiplas linguagens',
      'Analytics de interação',
      'API de terceiros'
    ]
  },
  {
    id: 'predictive-maintenance',
    name: 'Manutenção Preditiva',
    description: 'IA para previsão de falhas em equipamentos',
    icon: Wrench,
    complexity: 'hard',
    features: [
      'Análise preditiva',
      'Sensores IoT',
      'Machine learning',
      'Alertas preventivos',
      'Otimização de custos',
      'Relatórios de eficiência'
    ]
  },
  {
    id: 'robotic-process-automation',
    name: 'Automação Robótica de Processos',
    description: 'RPA para automatizar tarefas repetitivas',
    icon: Robot,
    complexity: 'hard',
    features: [
      'Designer de workflows',
      'Bots configuráveis',
      'Integração de sistemas',
      'Monitoramento de execução',
      'Escalabilidade automática',
      'ROI tracking'
    ]
  },
  {
    id: 'quantum-computing-platform',
    name: 'Plataforma de Computação Quântica',
    description: 'Acesso a recursos de computação quântica',
    icon: Atom,
    complexity: 'hard',
    features: [
      'Simulador quântico',
      'Algoritmos quânticos',
      'Acesso a hardware real',
      'SDK de desenvolvimento',
      'Otimização quântica',
      'Análise de resultados'
    ]
  },
  {
    id: 'neural-network-designer',
    name: 'Designer de Redes Neurais',
    description: 'Ferramenta visual para criar redes neurais',
    icon: Brain,
    complexity: 'hard',
    features: [
      'Editor visual',
      'Múltiplas arquiteturas',
      'Treinamento automático',
      'Visualização de dados',
      'Deploy em produção',
      'Monitoramento de modelo'
    ]
  },
  {
    id: 'edge-ai-platform',
    name: 'Plataforma de IA Edge',
    description: 'IA executada em dispositivos locais',
    icon: Smartphone,
    complexity: 'hard',
    features: [
      'Modelos otimizados',
      'Deploy em edge',
      'Inferência local',
      'Sincronização de modelos',
      'Telemetria de uso',
      'Otimização de hardware'
    ]
  },
  {
    id: 'synthetic-data-generator',
    name: 'Gerador de Dados Sintéticos',
    description: 'Criação de dados sintéticos para IA',
    icon: Database,
    complexity: 'hard',
    features: [
      'Geração de dados',
      'Preservação de privacidade',
      'Múltiplos tipos de dados',
      'Validação estatística',
      'Exportação de datasets',
      'Configuração de parâmetros'
    ]
  },
  {
    id: 'automated-testing-platform',
    name: 'Plataforma de Testes Automatizados',
    description: 'Testes automatizados com IA',
    icon: CheckCircle,
    complexity: 'hard',
    features: [
      'Testes de UI automatizados',
      'Geração de casos de teste',
      'Relatórios de cobertura',
      'Integração CI/CD',
      'Testes de performance',
      'Análise de falhas'
    ]
  },
  {
    id: 'code-review-ai',
    name: 'Revisão de Código com IA',
    description: 'IA para análise e revisão de código',
    icon: Code,
    complexity: 'hard',
    features: [
      'Análise de código',
      'Detecção de bugs',
      'Sugestões de melhoria',
      'Métricas de qualidade',
      'Integração com Git',
      'Relatórios de segurança'
    ]
  },
  {
    id: 'digital-twin-platform',
    name: 'Plataforma de Gêmeos Digitais',
    description: 'Criação e gestão de gêmeos digitais',
    icon: Copy,
    complexity: 'hard',
    features: [
      'Modelagem 3D',
      'Simulação em tempo real',
      'Integração com IoT',
      'Análise preditiva',
      'Visualização imersiva',
      'Otimização contínua'
    ]
  },
  {
    id: 'autonomous-vehicle-fleet',
    name: 'Frota de Veículos Autônomos',
    description: 'Gestão de frota de veículos autônomos',
    icon: Car,
    complexity: 'hard',
    features: [
      'Controle de frota',
      'Planejamento de rotas',
      'Manutenção preditiva',
      'Sistema de segurança',
      'Otimização de energia',
      'Compliance regulatório'
    ]
  },
  {
    id: 'smart-city-management',
    name: 'Gestão de Cidade Inteligente',
    description: 'Plataforma integrada para cidades inteligentes',
    icon: Building,
    complexity: 'hard',
    features: [
      'IoT urbano',
      'Gestão de tráfego',
      'Monitoramento ambiental',
      'Serviços cidadão',
      'Planejamento urbano',
      'Dashboard executivo'
    ]
  },
  {
    id: 'precision-agriculture',
    name: 'Agricultura de Precisão',
    description: 'Tecnologia para agricultura inteligente',
    icon: Tractor,
    complexity: 'hard',
    features: [
      'Monitoramento de culturas',
      'Drones para mapeamento',
      'Análise de solo',
      'Previsão de safra',
      'Otimização de recursos',
      'Sustentabilidade'
    ]
  },
  {
    id: 'renewable-energy-trading',
    name: 'Trading de Energia Renovável',
    description: 'Marketplace para energia limpa',
    icon: Sun,
    complexity: 'hard',
    features: [
      'Trading de energia',
      'Certificados verdes',
      'Grid balancing',
      'Previsão de geração',
      'Smart contracts',
      'Analytics de mercado'
    ]
  },
  {
    id: 'space-technology-platform',
    name: 'Plataforma de Tecnologia Espacial',
    description: 'Soluções para a indústria espacial',
    icon: Rocket,
    complexity: 'hard',
    features: [
      'Missão planning',
      'Satellite tracking',
      'Ground station management',
      'Data processing',
      'Communication protocols',
      'Mission analytics'
    ]
  },
  {
    id: 'biotechnology-lab',
    name: 'Laboratório de Biotecnologia',
    description: 'Gestão de laboratório biotecnológico',
    icon: Microscope,
    complexity: 'hard',
    features: [
      'Gestão de experimentos',
      'Sequenciamento genético',
      'Análise de dados',
      'Compliance regulatório',
      'Colaboração científica',
      'Propriedade intelectual'
    ]
  },
  {
    id: 'nanotechnology-simulator',
    name: 'Simulador de Nanotecnologia',
    description: 'Simulação molecular e nanotecnologia',
    icon: Atom,
    complexity: 'hard',
    features: [
      'Simulação molecular',
      'Design de nanomateriais',
      'Análise de propriedades',
      'Visualização 3D',
      'Cálculos quânticos',
      'Publicação de resultados'
    ]
  },
  {
    id: 'virtual-reality-training',
    name: 'Treinamento em Realidade Virtual',
    description: 'Plataforma de treinamento imersivo',
    icon: Headphones,
    complexity: 'hard',
    features: [
      'Simulações VR',
      'Cenários personalizáveis',
      'Avaliação de desempenho',
      'Multi-usuário',
      'Analytics de aprendizado',
      'Certificação digital'
    ]
  },
  {
    id: 'augmented-reality-commerce',
    name: 'Comércio em Realidade Aumentada',
    description: 'E-commerce com experiência AR',
    icon: Eye,
    complexity: 'hard',
    features: [
      'Try-before-buy AR',
      'Visualização 3D',
      'Configurador de produtos',
      'Social shopping',
      'Analytics de engajamento',
      'Cross-platform support'
    ]
  },
  {
    id: 'holographic-display-platform',
    name: 'Plataforma de Display Holográfico',
    description: 'Criação de conteúdo holográfico',
    icon: Projector,
    complexity: 'hard',
    features: [
      'Criação de hologramas',
      'Renderização 3D',
      'Controle gestual',
      'Múltiplas plataformas',
      'Streaming holográfico',
      'Colaboração espacial'
    ]
  },
  {
    id: 'brain-computer-interface',
    name: 'Interface Cérebro-Computador',
    description: 'Controle de sistemas via sinais neurais',
    icon: Brain,
    complexity: 'hard',
    features: [
      'Processamento de sinais EEG',
      'Machine learning neural',
      'Controle de dispositivos',
      'Calibração de usuário',
      'Feedback em tempo real',
      'Aplicações médicas'
    ]
  },
  {
    id: 'robotic-surgery-platform',
    name: 'Plataforma de Cirurgia Robótica',
    description: 'Assistência robótica para cirurgias',
    icon: Activity,
    complexity: 'hard',
    features: [
      'Controle robótico',
      'Precisão milimétrica',
      'Feedback háptico',
      'Visualização 3D',
      'Planejamento cirúrgico',
      'Teleoperation'
    ]
  },
  {
    id: 'personalized-medicine',
    name: 'Medicina Personalizada',
    description: 'Tratamentos baseados em genética',
    icon: Dna,
    complexity: 'hard',
    features: [
      'Análise genômica',
      'Predição de riscos',
      'Terapias personalizadas',
      'Farmacogenômica',
      'Biomarcadores',
      'Medicina de precisão'
    ]
  },
  {
    id: 'telemedicine-ai',
    name: 'Telemedicina com IA',
    description: 'Consultas médicas assistidas por IA',
    icon: Stethoscope,
    complexity: 'hard',
    features: [
      'Diagnóstico assistido',
      'Análise de imagens médicas',
      'Triagem automática',
      'Prescrição inteligente',
      'Monitoramento remoto',
      'Interoperabilidade'
    ]
  },
  {
    id: 'wearable-health-platform',
    name: 'Plataforma de Wearables de Saúde',
    description: 'Ecossistema de dispositivos de saúde',
    icon: Watch,
    complexity: 'hard',
    features: [
      'Múltiplos wearables',
      'Monitoramento contínuo',
      'Alertas de saúde',
      'Integração médica',
      'Analytics preditivos',
      'Compliance HIPAA'
    ]
  },
  {
    id: 'mental-health-ai',
    name: 'IA para Saúde Mental',
    description: 'Assistente de IA para bem-estar mental',
    icon: Brain,
    complexity: 'hard',
    features: [
      'Análise de humor',
      'Terapia cognitiva digital',
      'Detecção de crises',
      'Exercícios personalizados',
      'Monitoramento de progresso',
      'Integração com terapeutas'
    ]
  },
  {
    id: 'pharmaceutical-research',
    name: 'Pesquisa Farmacêutica',
    description: 'Plataforma para desenvolvimento de medicamentos',
    icon: Pill,
    complexity: 'hard',
    features: [
      'Drug discovery',
      'Ensaios clínicos',
      'Análise molecular',
      'Regulatory compliance',
      'Colaboração científica',
      'IP management'
    ]
  }
];
