import { 
  ShoppingCart, 
  Store, 
  Package, 
  CreditCard, 
  BarChart3, 
  Users, 
  Briefcase, 
  Building, 
  Truck, 
  MapPin, 
  Phone,
  Calculator,
  Globe,
  Brain,
  Code,
  Settings,
  Zap,
  Bot,
  Activity,
  Shield,
  CheckCircle,
  FileText,
  Calendar,
  MessageSquare,
  Timer,
  Target,
  TrendingUp,
  DollarSign,
  PieChart,
  Layers,
  Database,
  Cloud,
  Lock,
  Key,
  Mail,
  Bell,
  Search,
  Filter,
  Edit,
  Upload,
  Download,
  Share,
  Copy,
  Trash,
  Plus,
  Minus,
  Star,
  Heart,
  ThumbsUp,
  Eye,
  Camera,
  Video,
  Image,
  Link,
  ExternalLink,
  Home,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Maximize,
  Minimize,
  RotateCcw,
  RefreshCw,
  Save,
  Bookmark,
  Flag,
  Award,
  Medal,
  Trophy,
  Crown,
  Gem,
  Coins,
  Banknote,
  Wallet,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,
  Server,
  HardDrive,
  Cpu,
  MemoryStick,
  Wifi,
  Bluetooth,
  Usb,
  Battery,
  Power,
  Plug,
  Cable,
  Router,
  Antenna,
  Signal,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Stop,
  Rewind,
  FastForward,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Headphones,
  Mic,
  MicOff,
  Speaker,
  Radio,
  Disc,
  Music,
  Film,
  Tv,
  Theater,
  Gamepad2,
  Joystick,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Puzzle,
  Crosshair,
  Radar,
  Compass,
  Navigation,
  Map,
  Route,
  Car,
  Bus,
  Train,
  Plane,
  Bike,
  Ship,
  Rocket,
  Helicopter,
  Ambulance,
  Taxi,
  TrendingDown,
  BarChart,
  LineChart,
  AreaChart,
  ScatterChart,
  Inbox,
  Send,
  Reply,
  ReplyAll,
  Forward,
  Archive,
  Trash2,
  Spam,
  MailOpen,
  MailCheck,
  AtSign,
  Hash,
  Percent,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  List,
  ListOrdered,
  Quote,
  Code2,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  Folder,
  FolderOpen,
  File,
  FileEdit,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FileSpreadsheet,
  FileBarChart,
  FileLineChart,
  ClipboardList,
  Clipboard,
  ClipboardCheck,
  ClipboardX,
  ClipboardCopy,
  Scissors,
  PaintBucket,
  Palette,
  Brush,
  Pen,
  PenTool,
  Highlighter,
  Eraser,
  Ruler,
  Move,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Pentagon,
  Octagon,
  Diamond,
  RectangleHorizontal,
  RectangleVertical,
  Shapes,
  Grid,
  Layout,
  Sidebar,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  SplitSquareHorizontal,
  SplitSquareVertical,
  Columns,
  Rows,
  Table,
  Clock,
  Watch,
  Stopwatch,
  Hourglass,
  Sunrise,
  Sunset,
  Sun,
  Moon,
  Stars,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Umbrella,
  Rainbow,
  Snowflake,
  Thermometer,
  Wind,
  Tornado,
  Volcano,
  Mountain,
  TreePine,
  Trees,
  Flower,
  Flower2,
  Sprout,
  Leaf,
  Bug,
  Fish,
  Bird,
  Rabbit,
  Squirrel,
  Dog,
  Cat,
  Horse,
  Cow,
  Pig,
  Sheep,
  Chicken,
  Egg,
  Bone,
  Footprints,
  Paw,
  Apple,
  Cherry,
  Grape,
  Orange,
  Banana,
  Strawberry,
  Carrot,
  Corn,
  Pizza,
  Sandwich,
  Cookie,
  Cake,
  IceCream,
  Coffee,
  Tea,
  Beer,
  Wine,
  Martini,
  Soup,
  Salad,
  ChefHat,
  UtensilsCrossed,
  Fork,
  Spoon,
  Knife,
  Plate,
  Glass,
  Bottle,
  Can,
  Baby,
  Child,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UsersRound,
  UserRound,
  UserSquare,
  UserCircle,
  Contact,
  Contacts,
  AddressBook,
  IdCard,
  Badge,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  ShieldBan,
  Fingerprint,
  Scan,
  QrCode,
  Barcode,
  Tag,
  Tags,
  NotepadText,
  StickyNote,
  Pushpin,
  Paperclip,
  Stapler,
  Abacus,
  Protractor,
  Microscope,
  Telescope,
  Magnet,
  Atom,
  Dna,
  Pill,
  Syringe,
  Bandage,
  Stethoscope,
  XRay,
  Pulse,
  HeartPulse,
  Lightbulb,
  Flashlight,
  Candle,
  Fire,
  Flame,
  Spark,
  Earth,
  Satellite,
  Ufo
} from 'lucide-react';

import { ProjectTemplate } from '../projectTemplates';

export const businessTemplates: ProjectTemplate[] = [
  {
    id: 'ecommerce',
    name: 'E-commerce Platform',
    description: 'Plataforma completa de comércio eletrônico com carrinho, pagamentos e gestão de produtos',
    icon: ShoppingCart,
    complexity: 'medium',
    features: [
      'Catálogo de produtos',
      'Carrinho de compras',
      'Sistema de pagamento',
      'Painel administrativo',
      'Gestão de pedidos',
      'Sistema de avaliações'
    ]
  },
  {
    id: 'marketplace',
    name: 'Marketplace Multi-vendor',
    description: 'Marketplace para múltiplos vendedores com comissões e gestão centralizada',
    icon: Store,
    complexity: 'hard',
    features: [
      'Multi-vendedores',
      'Sistema de comissões',
      'Gestão de produtos',
      'Painel do vendedor',
      'Sistema de disputas',
      'Analytics avançado'
    ]
  },
  {
    id: 'inventory',
    name: 'Sistema de Inventário',
    description: 'Controle completo de estoque com código de barras e relatórios',
    icon: Package,
    complexity: 'medium',
    features: [
      'Controle de estoque',
      'Código de barras',
      'Relatórios detalhados',
      'Alertas de estoque baixo',
      'Gestão de fornecedores',
      'Histórico de movimentações'
    ]
  },
  {
    id: 'pos-system',
    name: 'Sistema PDV',
    description: 'Point of Sale completo para lojas físicas',
    icon: CreditCard,
    complexity: 'medium',
    features: [
      'Vendas rápidas',
      'Múltiplas formas de pagamento',
      'Impressão de cupons',
      'Controle de caixa',
      'Relatórios de vendas',
      'Gestão de funcionários'
    ]
  },
  {
    id: 'analytics-dashboard',
    name: 'Dashboard Analytics',
    description: 'Painel de análise de dados em tempo real',
    icon: BarChart3,
    complexity: 'medium',
    features: [
      'Visualização de dados',
      'Relatórios customizáveis',
      'Métricas em tempo real',
      'Exportação de dados',
      'Alerts automáticos',
      'Integração com APIs'
    ]
  },
  {
    id: 'crm-system',
    name: 'Sistema CRM',
    description: 'Gestão completa de relacionamento com clientes',
    icon: Users,
    complexity: 'hard',
    features: [
      'Gestão de leads',
      'Pipeline de vendas',
      'Histórico de interações',
      'Automação de marketing',
      'Relatórios de performance',
      'Integração com email'
    ]
  },
  {
    id: 'booking-system',
    name: 'Sistema de Agendamento',
    description: 'Plataforma de agendamento online para serviços',
    icon: Calendar,
    complexity: 'medium',
    features: [
      'Calendário interativo',
      'Gestão de horários',
      'Notificações automáticas',
      'Pagamento online',
      'Gestão de clientes',
      'Relatórios de ocupação'
    ]
  },
  {
    id: 'invoice-generator',
    name: 'Gerador de Faturas',
    description: 'Sistema completo para criação e gestão de faturas',
    icon: FileText,
    complexity: 'easy',
    features: [
      'Criação de faturas',
      'Templates customizáveis',
      'Controle de pagamentos',
      'Relatórios financeiros',
      'Envio por email',
      'Gestão de clientes'
    ]
  },
  {
    id: 'chat-support',
    name: 'Chat de Suporte',
    description: 'Sistema de chat em tempo real para atendimento ao cliente',
    icon: MessageSquare,
    complexity: 'medium',
    features: [
      'Chat em tempo real',
      'Sistema de tickets',
      'Histórico de conversas',
      'Múltiplos operadores',
      'Notificações push',
      'Integração com CRM'
    ]
  },
  {
    id: 'donation-platform',
    name: 'Plataforma de Doações',
    description: 'Sistema para campanhas de arrecadação e doações online',
    icon: Heart,
    complexity: 'medium',
    features: [
      'Campanhas de doação',
      'Processamento de pagamentos',
      'Metas e progresso',
      'Certificados de doação',
      'Compartilhamento social',
      'Relatórios de arrecadação'
    ]
  },
  {
    id: 'freelancer-platform',
    name: 'Plataforma Freelancer',
    description: 'Marketplace para freelancers e clientes se conectarem',
    icon: Briefcase,
    complexity: 'hard',
    features: [
      'Perfis de freelancers',
      'Sistema de propostas',
      'Escrow de pagamentos',
      'Avaliações e reviews',
      'Chat integrado',
      'Gestão de projetos'
    ]
  },
  {
    id: 'real-estate',
    name: 'Imobiliária Online',
    description: 'Plataforma para listagem e venda de imóveis',
    icon: Building,
    complexity: 'medium',
    features: [
      'Listagem de imóveis',
      'Busca avançada',
      'Galeria de fotos',
      'Tour virtual',
      'Agendamento de visitas',
      'Calculadora de financiamento'
    ]
  },
  {
    id: 'delivery-app',
    name: 'App de Delivery',
    description: 'Aplicativo completo de delivery com rastreamento',
    icon: Truck,
    complexity: 'hard',
    features: [
      'Pedidos online',
      'Rastreamento em tempo real',
      'Múltiplos restaurantes',
      'Sistema de avaliação',
      'Cupons de desconto',
      'Gestão de entregadores'
    ]
  },
  {
    id: 'location-finder',
    name: 'Localizador de Serviços',
    description: 'Encontre serviços próximos com geolocalização',
    icon: MapPin,
    complexity: 'medium',
    features: [
      'Geolocalização',
      'Busca por proximidade',
      'Avaliações de usuários',
      'Informações de contato',
      'Rotas e direções',
      'Filtros avançados'
    ]
  },
  {
    id: 'voip-system',
    name: 'Sistema VoIP',
    description: 'Sistema de telefonia pela internet para empresas',
    icon: Phone,
    complexity: 'hard',
    features: [
      'Chamadas VoIP',
      'Central telefônica',
      'Gravação de chamadas',
      'Relatórios de uso',
      'Múltiplas linhas',
      'Integração com CRM'
    ]
  },
  {
    id: 'ai-chatbot',
    name: 'Chatbot com IA',
    description: 'Assistente virtual inteligente para atendimento',
    icon: Bot,
    complexity: 'hard',
    features: [
      'Processamento de linguagem natural',
      'Respostas inteligentes',
      'Integração com sistemas',
      'Aprendizado contínuo',
      'Múltiplos canais',
      'Analytics de conversas'
    ]
  },
  {
    id: 'project-management',
    name: 'Gestão de Projetos',
    description: 'Ferramenta completa para gerenciamento de projetos',
    icon: Target,
    complexity: 'hard',
    features: [
      'Cronograma de tarefas',
      'Gráfico de Gantt',
      'Gestão de equipes',
      'Controle de tempo',
      'Relatórios de progresso',
      'Integração com calendário'
    ]
  },
  {
    id: 'social-network',
    name: 'Rede Social',
    description: 'Plataforma de rede social com recursos modernos',
    icon: Users,
    complexity: 'hard',
    features: [
      'Feed de notícias',
      'Sistema de amizades',
      'Mensagens privadas',
      'Grupos e comunidades',
      'Compartilhamento de mídia',
      'Sistema de notificações'
    ]
  },
  {
    id: 'learning-platform',
    name: 'Plataforma de Ensino',
    description: 'Sistema completo para cursos online',
    icon: Brain,
    complexity: 'hard',
    features: [
      'Criação de cursos',
      'Vídeo aulas',
      'Exercícios interativos',
      'Certificados',
      'Progresso do aluno',
      'Fórum de discussão'
    ]
  },
  {
    id: 'music-streaming',
    name: 'Streaming de Música',
    description: 'Plataforma de streaming musical',
    icon: Music,
    complexity: 'hard',
    features: [
      'Biblioteca de músicas',
      'Playlists personalizadas',
      'Recomendações IA',
      'Player avançado',
      'Modo offline',
      'Compartilhamento social'
    ]
  },
  {
    id: 'video-platform',
    name: 'Plataforma de Vídeos',
    description: 'Sistema de compartilhamento de vídeos',
    icon: Video,
    complexity: 'hard',
    features: [
      'Upload de vídeos',
      'Streaming adaptativo',
      'Sistema de comentários',
      'Canais de usuários',
      'Monetização',
      'Analytics detalhados'
    ]
  },
  {
    id: 'blockchain-wallet',
    name: 'Carteira Blockchain',
    description: 'Carteira digital para criptomoedas',
    icon: Wallet,
    complexity: 'hard',
    features: [
      'Múltiplas criptomoedas',
      'Transações seguras',
      'Histórico completo',
      'Exchange integrado',
      'Staking de tokens',
      'DeFi integration'
    ]
  },
  {
    id: 'iot-dashboard',
    name: 'Dashboard IoT',
    description: 'Central de controle para dispositivos IoT',
    icon: Wifi,
    complexity: 'hard',
    features: [
      'Gestão de dispositivos',
      'Monitoramento em tempo real',
      'Automação de regras',
      'Alertas inteligentes',
      'Análise de dados',
      'Controle remoto'
    ]
  },
  {
    id: 'ar-shopping',
    name: 'Shopping com Realidade Aumentada',
    description: 'E-commerce com experiência AR',
    icon: Eye,
    complexity: 'hard',
    features: [
      'Try-before-buy AR',
      'Visualização 3D',
      'Configurador de produtos',
      'Social shopping',
      'Analytics de engajamento',
      'Cross-platform support'
    ]
  },
  {
    id: 'smart-home',
    name: 'Casa Inteligente',
    description: 'Sistema de automação residencial',
    icon: Home,
    complexity: 'hard',
    features: [
      'Controle de dispositivos',
      'Automação por cenários',
      'Segurança integrada',
      'Economia de energia',
      'Controle por voz',
      'App mobile'
    ]
  },
  {
    id: 'telemedicine',
    name: 'Telemedicina',
    description: 'Plataforma para consultas médicas online',
    icon: Stethoscope,
    complexity: 'hard',
    features: [
      'Consultas por vídeo',
      'Prontuário eletrônico',
      'Prescrição digital',
      'Agendamento online',
      'Histórico médico',
      'Integração com laboratórios'
    ]
  },
  {
    id: 'fintech-app',
    name: 'Aplicativo Fintech',
    description: 'Solução financeira digital completa',
    icon: DollarSign,
    complexity: 'hard',
    features: [
      'Conta digital',
      'Cartão virtual',
      'Investimentos',
      'Empréstimos',
      'Cashback',
      'Open Banking'
    ]
  },
  {
    id: 'carbon-tracker',
    name: 'Rastreador de Pegada de Carbono',
    description: 'Monitor de sustentabilidade pessoal',
    icon: LeafIcon,
    complexity: 'medium',
    features: [
      'Cálculo de pegada de carbono',
      'Dicas de sustentabilidade',
      'Metas ambientais',
      'Offset de carbono',
      'Comparação social',
      'Certificados verdes'
    ]
  },
  {
    id: 'legal-tech',
    name: 'Plataforma Jurídica Tech',
    description: 'Automação de serviços jurídicos',
    icon: Scale,
    complexity: 'hard',
    features: [
      'Contratos automatizados',
      'Consultas jurídicas online',
      'Gestão de processos',
      'IA para análise legal',
      'Assinatura digital',
      'Compliance automático'
    ]
  },
  {
    id: 'quantum-simulator',
    name: 'Simulador Quântico',
    description: 'Plataforma de computação quântica simulada',
    icon: Atom,
    complexity: 'hard',
    features: [
      'Algoritmos quânticos',
      'Simulação de circuitos',
      'Visualização quântica',
      'SDK de desenvolvimento',
      'Otimização quântica',
      'Análise de resultados'
    ]
  },
  {
    id: 'space-mission',
    name: 'Controle de Missão Espacial',
    description: 'Sistema de controle para missões espaciais',
    icon: Satellite,
    complexity: 'hard',
    features: [
      'Telemetria em tempo real',
      'Controle de trajetória',
      'Comunicação satelital',
      'Planejamento de missão',
      'Análise de dados',
      'Simulação orbital'
    ]
  }
];
