import { 
  CheckCircle, 
  Calculator, 
  Cloud, 
  FileText, 
  Calendar, 
  BarChart3, 
  Search, 
  Download, 
  Upload, 
  Code, 
  Database, 
  Settings, 
  Lock, 
  Key, 
  Shield, 
  Wifi, 
  Smartphone, 
  Globe, 
  Map, 
  Camera, 
  Image, 
  Palette, 
  PenTool, 
  Music, 
  Video, 
  Mic, 
  Edit, 
  Copy, 
  Save, 
  Folder, 
  File, 
  Archive, 
  Trash, 
  Star, 
  Heart, 
  Users, 
  MessageSquare, 
  Mail, 
  Phone, 
  Bell, 
  Clock, 
  Timer, 
  Target, 
  TrendingUp, 
  Activity, 
  Award, 
  Trophy, 
  Gem, 
  Coins, 
  DollarSign, 
  ShoppingCart, 
  Package, 
  Truck, 
  Home, 
  Building, 
  Car, 
  Plane, 
  Train, 
  Bus, 
  Bike, 
  Route, 
  Navigation, 
  Compass, 
  Sun, 
  Moon, 
  CloudRain, 
  Thermometer, 
  Wind, 
  Umbrella, 
  TreePine, 
  Leaf, 
  Flower, 
  Bug, 
  Fish, 
  Dog, 
  Cat, 
  Apple, 
  Coffee, 
  Pizza, 
  Gamepad2, 
  Book, 
  Lightbulb, 
  Brain, 
  Wrench, 
  Hammer, 
  Paintbrush, 
  Ruler, 
  Scissors, 
  Flashlight, 
  Battery, 
  Plug, 
  Zap, 
  Signal, 
  Antenna, 
  Radio, 
  Tv, 
  Monitor, 
  Laptop, 
  Tablet, 
  HardDrive, 
  Server, 
  CircuitBoard, 
  MemoryStick, 
  Usb, 
  Bluetooth, 
  MousePointer, 
  Keyboard, 
  Printer, 
  Webcam, 
  Headphones, 
  Speaker, 
  Volume2, 
  Play, 
  Pause, 
  SkipForward, 
  SkipBack, 
  FastForward, 
  Rewind, 
  Repeat, 
  Shuffle, 
  EyeOff, 
  RotateCcw, 
  RefreshCw, 
  Maximize, 
  Minimize, 
  ZoomIn, 
  ZoomOut, 
  Focus, 
  Grid, 
  Layers, 
  Move, 
  Crop, 
  Filter, 
  Contrast, 
  Pen, 
  Eraser, 
  Brush, 
  PaintBucket, 
  Type, 
  AlignLeft, 
  AlignCenter, 
  AlignRight, 
  Bold, 
  Italic, 
  Underline, 
  Quote, 
  List, 
  Square, 
  Circle, 
  Triangle, 
  Diamond, 
  Hexagon, 
  Plus, 
  Minus, 
  X, 
  Check, 
  ChevronUp, 
  ChevronDown, 
  ChevronLeft, 
  ChevronRight, 
  ArrowUp, 
  ArrowDown, 
  ArrowLeft, 
  ArrowRight, 
  CornerDownLeft, 
  CornerDownRight, 
  CornerUpLeft, 
  CornerUpRight, 
  MoreHorizontal, 
  MoreVertical, 
  Menu, 
  Info, 
  HelpCircle, 
  Cog, 
  Sliders, 
  ToggleLeft, 
  ToggleRight, 
  Volume1, 
  VolumeX, 
  Bookmark, 
  BookmarkPlus, 
  Flag, 
  Tag, 
  Tags, 
  Hash, 
  AtSign, 
  Link, 
  ExternalLink, 
  Share, 
  Share2, 
  Repeat2, 
  RotateCw, 
  TrendingDown, 
  BarChart, 
  LineChart, 
  PieChart, 
  AreaChart, 
  ScatterChart, 
  Eye, 
  CloudDownload, 
  CloudUpload, 
  HardDriveDownload, 
  HardDriveUpload, 
  FolderDown, 
  FolderUp, 
  FileDown, 
  FileUp, 
  Import, 
  Inbox, 
  Send, 
  Reply, 
  ReplyAll, 
  Forward, 
  Trash2, 
  RefreshCcw, 
  Undo, 
  Redo, 
  History, 
  Clock3, 
  Clock6, 
  Clock9, 
  Clock12, 
  AlarmClock, 
  Watch, 
  Hourglass, 
  Sunrise, 
  Sunset, 
  CloudSun, 
  CloudMoon, 
  Snowflake, 
  CloudSnow, 
  CloudLightning, 
  Rainbow, 
  Mountain, 
  Waves, 
  Trees, 
  Sprout, 
  Flower2, 
  Worm, 
  Bird, 
  Rabbit, 
  Squirrel, 
  Footprints, 
  PawPrint, 
  Bone, 
  Cherry, 
  Grape, 
  Banana, 
  Carrot, 
  Egg, 
  Milk, 
  Sandwich, 
  Cookie, 
  Cake, 
  IceCream, 
  Beer, 
  Wine, 
  Martini, 
  Soup, 
  UtensilsCrossed, 
  ChefHat, 
  Baby, 
  UserPlus, 
  UserMinus, 
  UserCheck, 
  UserX, 
  UsersRound, 
  UserRound, 
  UserSquare, 
  Contact, 
  IdCard, 
  Badge, 
  ShieldCheck, 
  ShieldAlert, 
  ShieldX, 
  Fingerprint, 
  Scan, 
  QrCode, 
  Barcode, 
  NotepadText, 
  StickyNote, 
  Paperclip, 
  Unlink, 
  Anchor, 
  Magnet, 
  Atom, 
  Dna, 
  Microscope, 
  Telescope, 
  Pill, 
  Syringe, 
  Bandage, 
  Stethoscope, 
  HeartPulse, 
  Flame, 
  Earth, 
  Satellite, 
  Rocket, 
  BookOpen,
  Smile,
  ShoppingBag,
  Droplets,
  Terminal,
  GitBranch,
  Layers as LayersIcon,
  Bot,
  Cpu,
  HardDrive as HardDriveIcon,
  Workflow,
  Boxes,
  Users2,
  Briefcase,
  GraduationCap,
  Scale,
  AlertTriangle,
  XCircle,
  CheckCircle2,
  Loader2,
  Crown,
  Shield as ShieldIcon,
  TrendingUp as TrendingUpIcon,
  BarChart2,
  PieChart as PieChartIcon,
  Activity as ActivityIcon,
  Zap as ZapIcon
} from 'lucide-react';

import { ProjectTemplate } from '../projectTemplates';

export const utilityTemplates: ProjectTemplate[] = [
  {
    id: 'todo-app',
    name: 'Aplicativo de Tarefas',
    description: 'Um gerenciador de tarefas simples e eficiente para organizar sua rotina',
    icon: CheckCircle,
    complexity: 'easy',
    features: [
      'Adicionar e remover tarefas',
      'Marcar como concluído',
      'Filtros por status',
      'Armazenamento local',
      'Interface responsiva'
    ]
  },
  {
    id: 'note-taking-app',
    name: 'Aplicativo de Notas',
    description: 'Organize seus pensamentos com um sistema de notas avançado',
    icon: FileText,
    complexity: 'medium',
    features: [
      'Editor de texto rico',
      'Organização por pastas',
      'Busca avançada',
      'Sincronização na nuvem',
      'Marcação com tags',
      'Exportação em múltiplos formatos'
    ]
  },
  {
    id: 'weather-app',
    name: 'App de Clima',
    description: 'Aplicativo de previsão do tempo com dados em tempo real',
    icon: Cloud,
    complexity: 'medium',
    features: [
      'Previsão atual e semanal',
      'Múltiplas cidades',
      'Gráficos interativos',
      'Alertas meteorológicos',
      'Geolocalização automática',
      'Dados históricos'
    ]
  },
  {
    id: 'calculator',
    name: 'Calculadora Avançada',
    description: 'Calculadora científica com funções matemáticas completas',
    icon: Calculator,
    complexity: 'easy',
    features: [
      'Operações básicas',
      'Funções científicas',
      'Histórico de cálculos',
      'Conversão de unidades',
      'Modo programador',
      'Gráficos de funções'
    ]
  },
  {
    id: 'password-manager',
    name: 'Gerenciador de Senhas',
    description: 'Armazene e gerencie suas senhas com segurança',
    icon: Lock,
    complexity: 'hard',
    features: [
      'Criptografia AES-256',
      'Gerador de senhas',
      'Preenchimento automático',
      'Sincronização segura',
      'Autenticação biométrica',
      'Auditoria de segurança'
    ]
  },
  {
    id: 'file-manager',
    name: 'Gerenciador de Arquivos',
    description: 'Organize e gerencie seus arquivos de forma eficiente',
    icon: Folder,
    complexity: 'medium',
    features: [
      'Navegação por pastas',
      'Busca de arquivos',
      'Pré-visualização',
      'Compressão de arquivos',
      'Compartilhamento',
      'Backup automático'
    ]
  },
  {
    id: 'alarm-clock',
    name: 'Despertador',
    description: 'Despertador personalizável com múltiplas funcionalidades',
    icon: Clock,
    complexity: 'easy',
    features: [
      'Múltiplos alarmes',
      'Sons personalizados',
      'Soneca inteligente',
      'Timer e cronômetro',
      'Fuso horário mundial',
      'Modo noturno'
    ]
  },
  {
    id: 'unit-converter',
    name: 'Conversor de Unidades',
    description: 'Converta entre diferentes unidades de medida',
    icon: Settings,
    complexity: 'easy',
    features: [
      'Conversão de medidas',
      'Moedas em tempo real',
      'Temperatura',
      'Peso e volume',
      'Velocidade e distância',
      'Histórico de conversões'
    ]
  },
  {
    id: 'qr-code-generator',
    name: 'Gerador de QR Code',
    description: 'Crie e leia códigos QR facilmente',
    icon: QrCode,
    complexity: 'easy',
    features: [
      'Geração de QR codes',
      'Scanner de códigos',
      'Múltiplos formatos',
      'Personalização visual',
      'Histórico de códigos',
      'Compartilhamento rápido'
    ]
  },
  {
    id: 'color-picker',
    name: 'Seletor de Cores',
    description: 'Ferramenta completa para trabalhar com cores',
    icon: Palette,
    complexity: 'medium',
    features: [
      'Seletor de cores',
      'Paletas de cores',
      'Conversão entre formatos',
      'Análise de contraste',
      'Gerador de gradientes',
      'Biblioteca de cores'
    ]
  },
  {
    id: 'image-editor',
    name: 'Editor de Imagens',
    description: 'Editor de imagens com ferramentas básicas e filtros',
    icon: Image,
    complexity: 'hard',
    features: [
      'Edição básica',
      'Filtros e efeitos',
      'Ajustes de cor',
      'Redimensionamento',
      'Texto e anotações',
      'Múltiplos formatos'
    ]
  },
  {
    id: 'screen-recorder',
    name: 'Gravador de Tela',
    description: 'Grave e compartilhe sua tela facilmente',
    icon: Video,
    complexity: 'hard',
    features: [
      'Gravação de tela',
      'Gravação de áudio',
      'Anotações em tempo real',
      'Múltiplas resoluções',
      'Edição básica',
      'Upload para nuvem'
    ]
  },
  {
    id: 'productivity-tracker',
    name: 'Monitor de Produtividade',
    description: 'Acompanhe e melhore sua produtividade',
    icon: TrendingUpIcon,
    complexity: 'medium',
    features: [
      'Rastreamento de tempo',
      'Análise de atividades',
      'Metas diárias',
      'Relatórios detalhados',
      'Bloqueio de distrações',
      'Gamificação'
    ]
  },
  {
    id: 'habit-tracker',
    name: 'Rastreador de Hábitos',
    description: 'Construa e mantenha hábitos saudáveis',
    icon: Target,
    complexity: 'easy',
    features: [
      'Múltiplos hábitos',
      'Streaks e estatísticas',
      'Lembretes personalizados',
      'Visualização de progresso',
      'Desafios mensais',
      'Recompensas virtuais'
    ]
  },
  {
    id: 'budget-planner',
    name: 'Planejador de Orçamento',
    description: 'Gerencie suas finanças pessoais',
    icon: DollarSign,
    complexity: 'medium',
    features: [
      'Orçamento mensal',
      'Categorização de gastos',
      'Metas de economia',
      'Relatórios financeiros',
      'Alertas de gastos',
      'Sincronização bancária'
    ]
  },
  {
    id: 'bookmark-manager',
    name: 'Gerenciador de Favoritos',
    description: 'Organize seus links e favoritos',
    icon: Bookmark,
    complexity: 'easy',
    features: [
      'Organização por categorias',
      'Tags personalizadas',
      'Busca rápida',
      'Sincronização multi-device',
      'Importação de navegadores',
      'Compartilhamento de coleções'
    ]
  },
  {
    id: 'recipe-organizer',
    name: 'Organizador de Receitas',
    description: 'Gerencie e descubra receitas culinárias',
    icon: ChefHat,
    complexity: 'medium',
    features: [
      'Biblioteca de receitas',
      'Lista de compras automática',
      'Timer de cozinha',
      'Planejamento de refeições',
      'Cálculo nutricional',
      'Compartilhamento social'
    ]
  },
  {
    id: 'password-generator',
    name: 'Gerador de Senhas',
    description: 'Gere senhas seguras e personalizadas',
    icon: Key,
    complexity: 'easy',
    features: [
      'Múltiplas opções de complexidade',
      'Senhas pronunciáveis',
      'Verificação de força',
      'Histórico de senhas',
      'Cópia automática',
      'Verificação de vazamentos'
    ]
  },
  {
    id: 'text-editor',
    name: 'Editor de Texto',
    description: 'Editor de texto com recursos avançados',
    icon: Edit,
    complexity: 'medium',
    features: [
      'Sintaxe highlighting',
      'Múltiplas abas',
      'Busca e substituição',
      'Plugins e extensões',
      'Modo escuro',
      'Colaboração em tempo real'
    ]
  },
  {
    id: 'url-shortener',
    name: 'Encurtador de URLs',
    description: 'Encurte e gerencie seus links',
    icon: Link,
    complexity: 'easy',
    features: [
      'URLs personalizadas',
      'Analytics de cliques',
      'QR codes automáticos',
      'Expiração de links',
      'Proteção por senha',
      'Bulk shortening'
    ]
  },
  {
    id: 'clipboard-manager',
    name: 'Gerenciador de Área de Transferência',
    description: 'Histórico e gestão da área de transferência',
    icon: Copy,
    complexity: 'easy',
    features: [
      'Histórico completo',
      'Busca no histórico',
      'Favoritos fixos',
      'Snippets reutilizáveis',
      'Sincronização multi-device',
      'Formatação automática'
    ]
  },
  {
    id: 'pomodoro-timer',
    name: 'Timer Pomodoro',
    description: 'Técnica Pomodoro para produtividade',
    icon: Timer,
    complexity: 'easy',
    features: [
      'Ciclos personalizáveis',
      'Sons de notificação',
      'Estatísticas de sessões',
      'Lista de tarefas integrada',
      'Bloqueio de distrações',
      'Relatórios semanais'
    ]
  },
  {
    id: 'markdown-editor',
    name: 'Editor Markdown',
    description: 'Editor de Markdown com preview em tempo real',
    icon: FileText,
    complexity: 'medium',
    features: [
      'Preview em tempo real',
      'Sintaxe highlighting',
      'Exportação para HTML/PDF',
      'Tabelas e diagramas',
      'Math expressions',
      'Temas personalizáveis'
    ]
  },
  {
    id: 'system-monitor',
    name: 'Monitor do Sistema',
    description: 'Monitore o desempenho do seu sistema',
    icon: ActivityIcon,
    complexity: 'hard',
    features: [
      'CPU e memória',
      'Processos ativos',
      'Uso de disco',
      'Rede e bandwidth',
      'Temperatura do sistema',
      'Histórico de performance'
    ]
  },
  {
    id: 'wifi-analyzer',
    name: 'Analisador Wi-Fi',
    description: 'Analise e otimize sua rede Wi-Fi',
    icon: Wifi,
    complexity: 'medium',
    features: [
      'Scan de redes próximas',
      'Força do sinal',
      'Canais menos congestionados',
      'Teste de velocidade',
      'Histórico de conexões',
      'Relatórios de qualidade'
    ]
  },
  {
    id: 'backup-utility',
    name: 'Utilitário de Backup',
    description: 'Faça backup de seus dados importantes',
    icon: Archive,
    complexity: 'medium',
    features: [
      'Backup automático',
      'Múltiplos destinos',
      'Compressão inteligente',
      'Versionamento de arquivos',
      'Restauração seletiva',
      'Agendamento flexível'
    ]
  },
  {
    id: 'disk-cleaner',
    name: 'Limpador de Disco',
    description: 'Libere espaço no seu disco rígido',
    icon: HardDriveIcon,
    complexity: 'easy',
    features: [
      'Análise de uso de disco',
      'Limpeza de arquivos temporários',
      'Duplicatas automáticas',
      'Cache de aplicativos',
      'Logs antigos',
      'Relatórios de limpeza'
    ]
  },
  {
    id: 'network-scanner',
    name: 'Scanner de Rede',
    description: 'Descubra dispositivos na sua rede',
    icon: Globe,
    complexity: 'medium',
    features: [
      'Scan de dispositivos',
      'Portas abertas',
      'Informações de sistema',
      'Wake-on-LAN',
      'Ping e traceroute',
      'Monitoramento contínuo'
    ]
  },
  {
    id: 'startup-manager',
    name: 'Gerenciador de Inicialização',
    description: 'Controle programas que iniciam com o sistema',
    icon: Rocket,
    complexity: 'easy',
    features: [
      'Lista de programas de inicialização',
      'Habilitar/desabilitar itens',
      'Impacto na inicialização',
      'Backup de configurações',
      'Recomendações inteligentes',
      'Tempo de boot'
    ]
  },
  {
    id: 'registry-cleaner',
    name: 'Limpador de Registro',
    description: 'Otimize o registro do Windows',
    icon: Settings,
    complexity: 'medium',
    features: [
      'Scan de problemas',
      'Backup automático',
      'Limpeza segura',
      'Otimização de performance',
      'Agendamento automático',
      'Relatórios detalhados'
    ]
  },
  {
    id: 'font-manager',
    name: 'Gerenciador de Fontes',
    description: 'Organize e gerencie suas fontes',
    icon: Type,
    complexity: 'easy',
    features: [
      'Preview de fontes',
      'Organização por categorias',
      'Ativação/desativação',
      'Comparação de fontes',
      'Busca avançada',
      'Exportação de coleções'
    ]
  },
  {
    id: 'screen-capture',
    name: 'Captura de Tela',
    description: 'Capture e edite screenshots',
    icon: Camera,
    complexity: 'medium',
    features: [
      'Captura de área selecionada',
      'Captura de janela',
      'Anotações e setas',
      'Upload automático',
      'Histórico de capturas',
      'Múltiplos formatos'
    ]
  },
  {
    id: 'api-tester',
    name: 'Testador de API',
    description: 'Teste e documente APIs REST',
    icon: Code,
    complexity: 'hard',
    features: [
      'Múltiplos métodos HTTP',
      'Headers customizados',
      'Autenticação integrada',
      'Histórico de requisições',
      'Documentação automática',
      'Testes automatizados'
    ]
  },
  {
    id: 'json-formatter',
    name: 'Formatador JSON',
    description: 'Formate e valide documentos JSON',
    icon: Code,
    complexity: 'easy',
    features: [
      'Formatação automática',
      'Validação de sintaxe',
      'Minificação',
      'Conversão para outros formatos',
      'Busca em objetos',
      'Comparação de JSONs'
    ]
  },
  {
    id: 'regex-tester',
    name: 'Testador de Regex',
    description: 'Teste e construa expressões regulares',
    icon: Search,
    complexity: 'medium',
    features: [
      'Teste em tempo real',
      'Explicação da regex',
      'Biblioteca de padrões',
      'Múltiplas linguagens',
      'Casos de teste',
      'Gerador automático'
    ]
  },
  {
    id: 'hash-generator',
    name: 'Gerador de Hash',
    description: 'Gere hashes criptográficos',
    icon: Hash,
    complexity: 'easy',
    features: [
      'Múltiplos algoritmos',
      'Hash de arquivos',
      'Verificação de integridade',
      'Comparação de hashes',
      'Batch processing',
      'Histórico de cálculos'
    ]
  },
  {
    id: 'base64-converter',
    name: 'Conversor Base64',
    description: 'Codifique e decodifique Base64',
    icon: Code,
    complexity: 'easy',
    features: [
      'Codificação/decodificação',
      'Suporte a arquivos',
      'URL encoding',
      'Múltiplos formatos',
      'Validação automática',
      'Batch conversion'
    ]
  },
  {
    id: 'lorem-generator',
    name: 'Gerador Lorem Ipsum',
    description: 'Gere texto placeholder Lorem Ipsum',
    icon: Type,
    complexity: 'easy',
    features: [
      'Múltiplos tipos de texto',
      'Controle de quantidade',
      'Formatos diferentes',
      'Idiomas alternativos',
      'Cópia automática',
      'Templates personalizados'
    ]
  }
];
