import {
  Code, Database, Globe, Smartphone, Users, ShoppingCart, Calendar, 
  CreditCard, BarChart, MessageSquare, Mail, Lock, Settings, Search,
  FileText, Image, Video, Music, Book, Newspaper, Camera, Mic,
  MapPin, Car, Plane, Train, Home, Building, Store, Factory,
  Heart, Activity, Pill, Stethoscope, Brain, Eye, Ear, Hand,
  Gamepad2, Trophy, Target, Dice1, Puzzle, Sword, Shield, Crown,
  Palette, Brush, Scissors, Ruler, PenTool, Layers, Grid, Move,
  Sun, Moon, Cloud, Umbrella, Snowflake, Thermometer, Wind, Zap,
  Leaf, TreePine, Flower, Bug, Fish, Bird, Cat, Dog, Rabbit, Star,
  Coins, TrendingDown, Calculator, Receipt, Banknote, Wallet,
  GraduationCap, BookOpen, Pencil, Backpack, Apple, Coffee, Pizza,
  Utensils, Wine, IceCream, Cake, Donut, Cookie, Sandwich, Salad,
  Dumbbell, Bike, Check, Award, Medal, Flag,
  Shirt, Watch, Glasses, Baby, Users2, UserPlus, UserMinus, UserCheck, UserX, Group,
  Truck, Package2, Boxes, Warehouse, Package, Box, Clipboard,
  Badge, Ribbon, Recycle, Trash, Archive, Folder, File, Upload, Download,
  TrendingUp, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, RotateCw,
  Play, Pause, SkipForward, SkipBack, Volume2, VolumeX,
  Monitor, Tablet, Mouse, Keyboard, Printer, Wifi, Bluetooth,
  Clock, Timer, AlarmClock, Hourglass, Calendar as CalendarIcon,
  Phone, MessageCircle, AtSign, Send, Inbox, Archive as ArchiveIcon,
  Share, ThumbsUp, ThumbsDown, Heart as HeartIcon,
  Sprout, Cherry, Grape, Banana,
  Wrench, Hammer, Drill, Pickaxe, Shovel,
  Paintbrush, PaintBucket, Eraser, Highlighter,
  Bot, Cpu, Server, CloudRain, Sparkles, GitBranch, Terminal,
  Shield as SecurityIcon, Network, HardDrive, Gauge, TestTube,
  FileCode, BookMarked, Headphones, Navigation, ShoppingBag,
  Plus, QrCode
} from 'lucide-react';

export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  subcategory?: string;
  difficulty: 'Fácil' | 'Médio' | 'Avançado';
  estimatedTime: string;
  icon: any;
  features: string[];
  tags: string[];
  tier: 'freemium' | 'pro' | 'business';
}

export const templateCategories = [
  {
    id: 'all',
    name: 'Todos',
    icon: Grid,
    description: 'Todos os templates disponíveis'
  },
  {
    id: 'ecommerce',
    name: 'E-commerce',
    icon: ShoppingCart,
    description: 'Lojas virtuais e marketplaces'
  },
  {
    id: 'social',
    name: 'Social & Comunicação',
    icon: Users,
    description: 'Redes sociais e comunicação'
  },
  {
    id: 'business',
    name: 'Negócios & Gestão',
    icon: Building,
    description: 'Ferramentas de gestão empresarial'
  },
  {
    id: 'health',
    name: 'Saúde & Bem-estar',
    icon: Heart,
    description: 'Saúde, fitness e bem-estar'
  },
  {
    id: 'education',
    name: 'Educação',
    icon: GraduationCap,
    description: 'Ensino e aprendizagem'
  },
  {
    id: 'food',
    name: 'Alimentação',
    icon: Utensils,
    description: 'Restaurantes e delivery'
  },
  {
    id: 'transport',
    name: 'Transporte',
    icon: Car,
    description: 'Logística e transporte'
  },
  {
    id: 'realestate',
    name: 'Imóveis',
    icon: Home,
    description: 'Imobiliárias e propriedades'
  },
  {
    id: 'productivity',
    name: 'Produtividade',
    icon: Zap,
    description: 'Ferramentas de produtividade'
  },
  {
    id: 'entertainment',
    name: 'Entretenimento',
    icon: Gamepad2,
    description: 'Jogos e entretenimento'
  },
  {
    id: 'marketing',
    name: 'Marketing Digital',
    icon: TrendingUp,
    description: 'Marketing e publicidade'
  },
  {
    id: 'finance',
    name: 'Finanças',
    icon: DollarSign,
    description: 'Gestão financeira'
  },
  {
    id: 'technology',
    name: 'Tecnologia',
    icon: Monitor,
    description: 'Ferramentas técnicas'
  }
];

export const projectTemplates: ProjectTemplate[] = [
  // E-commerce & Vendas
  {
    id: 'ecommerce-basic',
    name: 'Loja Online Básica',
    description: 'Plataforma completa de e-commerce com carrinho, pagamentos e gestão de produtos',
    category: 'ecommerce',
    subcategory: 'Loja Virtual',
    icon: ShoppingCart,
    color: 'from-green-500 to-emerald-600',
    features: ['Catálogo de produtos', 'Carrinho de compras', 'Sistema de pagamento', 'Painel administrativo'],
    techStack: ['React', 'Supabase', 'Stripe', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '2-3 dias'
  },
  {
    id: 'ecommerce-advanced',
    name: 'Marketplace Avançado',
    description: 'Marketplace multi-vendedores com avaliações, chat e sistema de comissões',
    category: 'ecommerce',
    subcategory: 'Marketplace',
    icon: Store,
    color: 'from-purple-500 to-pink-600',
    features: ['Multi-vendedores', 'Avaliações e comentários', 'Chat interno', 'Sistema de comissões'],
    techStack: ['Next.js', 'Supabase', 'Stripe', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias',
    popular: true
  },
  {
    id: 'social-network',
    name: 'Rede Social Básica',
    description: 'Rede social com feed, perfis, seguidores e curtidas',
    category: 'social',
    subcategory: 'Rede Social',
    icon: Users,
    color: 'from-blue-500 to-cyan-600',
    features: ['Feed de posts', 'Perfis de usuário', 'Sistema de seguidores', 'Curtidas e comentários'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'social-chat',
    name: 'App de Chat',
    description: 'Aplicativo de mensagens em tempo real com grupos e notificações',
    category: 'social',
    subcategory: 'Chat',
    icon: MessageSquare,
    color: 'from-indigo-500 to-purple-600',
    features: ['Mensagens em tempo real', 'Grupos de chat', 'Notificações push', 'Status online'],
    techStack: ['React', 'Supabase', 'Pusher', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'task-manager',
    name: 'Gerenciador de Tarefas',
    description: 'Aplicativo para criar, editar e organizar tarefas com prazos e prioridades',
    category: 'productivity',
    subcategory: 'Tarefas',
    icon: Check,
    color: 'from-yellow-500 to-orange-600',
    features: ['Listas de tarefas', 'Prazos e lembretes', 'Prioridades', 'Filtros e categorias'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'beginner',
    estimatedTime: '1-2 dias'
  },
  {
    id: 'calendar-app',
    name: 'Calendário e Agenda',
    description: 'Calendário interativo com eventos, lembretes e integração com Google Calendar',
    category: 'productivity',
    subcategory: 'Calendário',
    icon: CalendarIcon,
    color: 'from-red-500 to-pink-600',
    features: ['Eventos e lembretes', 'Visualização mensal/semanal', 'Integração Google Calendar'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'online-course',
    name: 'Plataforma de Cursos Online',
    description: 'Sistema para criar e vender cursos com vídeos, quizzes e certificados',
    category: 'education',
    subcategory: 'Cursos Online',
    icon: BookOpen,
    color: 'from-indigo-500 to-blue-600',
    features: ['Upload de vídeos', 'Quizzes interativos', 'Certificados digitais', 'Área do aluno'],
    techStack: ['Next.js', 'Supabase', 'Stripe', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias',
    popular: true
  },
  {
    id: 'language-learning',
    name: 'App de Aprendizado de Idiomas',
    description: 'Aplicativo para aprender idiomas com lições, flashcards e testes',
    category: 'education',
    subcategory: 'Aprendizado',
    icon: Globe,
    color: 'from-green-500 to-teal-600',
    features: ['Lições interativas', 'Flashcards', 'Testes e avaliações', 'Progresso do usuário'],
    techStack: ['React Native', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'health-tracker',
    name: 'Monitor de Saúde',
    description: 'App para acompanhar atividades físicas, alimentação e sono',
    category: 'health',
    subcategory: 'Monitoramento',
    icon: Heart,
    color: 'from-red-500 to-pink-600',
    features: ['Registro de atividades', 'Controle alimentar', 'Monitoramento do sono', 'Relatórios semanais'],
    techStack: ['React Native', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'telemedicine',
    name: 'Plataforma de Telemedicina',
    description: 'Consulta médica online com agendamento, videochamada e histórico',
    category: 'health',
    subcategory: 'Telemedicina',
    icon: Video,
    color: 'from-blue-500 to-cyan-600',
    features: ['Agendamento', 'Videochamada', 'Histórico de consultas', 'Prescrições digitais'],
    techStack: ['Next.js', 'Supabase', 'WebRTC', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-10 dias'
  },
  {
    id: 'budget-app',
    name: 'App de Orçamento Pessoal',
    description: 'Controle de gastos, receitas e metas financeiras pessoais',
    category: 'finance',
    subcategory: 'Orçamento',
    icon: Wallet,
    color: 'from-yellow-500 to-amber-600',
    features: ['Registro de despesas', 'Categorias personalizadas', 'Metas financeiras', 'Relatórios gráficos'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'invoice-system',
    name: 'Sistema de Faturamento',
    description: 'Gerar e enviar faturas para clientes com controle de pagamentos',
    category: 'finance',
    subcategory: 'Faturamento',
    icon: Receipt,
    color: 'from-purple-500 to-indigo-600',
    features: ['Criação de faturas', 'Envio por email', 'Controle de pagamentos', 'Relatórios'],
    techStack: ['Next.js', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'music-player',
    name: 'Player de Música',
    description: 'Aplicativo para ouvir músicas, criar playlists e compartilhar',
    category: 'entertainment',
    subcategory: 'Música',
    icon: Music,
    color: 'from-pink-500 to-red-600',
    features: ['Reprodução de músicas', 'Playlists', 'Compartilhamento', 'Favoritos'],
    techStack: ['React Native', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'video-streaming',
    name: 'Streaming de Vídeo',
    description: 'Plataforma para transmitir vídeos ao vivo e sob demanda',
    category: 'entertainment',
    subcategory: 'Vídeo',
    icon: Video,
    color: 'from-red-500 to-orange-600',
    features: ['Transmissão ao vivo', 'Vídeos sob demanda', 'Chat ao vivo', 'Assinaturas'],
    techStack: ['Next.js', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'travel-planner',
    name: 'Planejador de Viagens',
    description: 'Organize roteiros, reservas e orçamentos para suas viagens',
    category: 'travel',
    subcategory: 'Planejamento',
    icon: MapPin,
    color: 'from-teal-500 to-cyan-600',
    features: ['Roteiros personalizados', 'Reservas integradas', 'Orçamento de viagem', 'Compartilhamento'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'hotel-booking',
    name: 'Reserva de Hotéis',
    description: 'Sistema para buscar, reservar e gerenciar hospedagens',
    category: 'travel',
    subcategory: 'Reserva',
    icon: Building,
    color: 'from-blue-500 to-indigo-600',
    features: ['Busca de hotéis', 'Reservas online', 'Avaliações', 'Gestão de reservas'],
    techStack: ['Next.js', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-7 dias'
  },
  {
    id: 'crm-basic',
    name: 'CRM Básico',
    description: 'Gerencie clientes, vendas e contatos em um só lugar',
    category: 'business',
    subcategory: 'CRM',
    icon: Users,
    color: 'from-green-600 to-emerald-700',
    features: ['Cadastro de clientes', 'Funil de vendas', 'Notas e tarefas', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'project-management',
    name: 'Gestão de Projetos',
    description: 'Organize equipes, tarefas e prazos com painéis e gráficos',
    category: 'business',
    subcategory: 'Gestão',
    icon: Clipboard,
    color: 'from-blue-600 to-cyan-700',
    features: ['Quadros Kanban', 'Calendário', 'Gráficos de progresso', 'Colaboração em equipe'],
    techStack: ['Next.js', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'marketplace-multivendor',
    name: 'Marketplace Multi-vendor',
    description: 'Plataforma completa para múltiplos vendedores com gestão de produtos, pagamentos e logística',
    category: 'ecommerce',
    subcategory: 'Marketplace',
    icon: Store,
    color: 'from-purple-500 to-pink-600',
    features: ['Painel de vendedores', 'Gestão de comissões', 'Sistema de avaliações', 'Relatórios de vendas', 'Chat interno'],
    techStack: ['Next.js', 'Supabase', 'Stripe Connect', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-10 dias',
    popular: true
  },
  {
    id: 'dropshipping-platform',
    name: 'Plataforma de Dropshipping',
    description: 'Sistema automatizado para dropshipping com integração de fornecedores e gestão de pedidos',
    category: 'ecommerce',
    subcategory: 'Dropshipping',
    icon: Package2,
    color: 'from-blue-500 to-cyan-600',
    features: ['Importação automática de produtos', 'Sincronização de estoque', 'Automação de pedidos', 'Integração com fornecedores'],
    techStack: ['Next.js', 'Supabase', 'APIs externas', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'subscription-box',
    name: 'Sistema de Subscription Box',
    description: 'Plataforma para venda de assinaturas mensais com curadoria de produtos',
    category: 'ecommerce',
    subcategory: 'Assinaturas',
    icon: Box,
    color: 'from-orange-500 to-red-600',
    features: ['Assinaturas recorrentes', 'Curadoria de produtos', 'Gestão de inventário', 'Portal do assinante'],
    techStack: ['React', 'Supabase', 'Stripe Subscriptions', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'community-platform',
    name: 'Plataforma de Comunidade',
    description: 'Rede social focada em comunidades com fóruns, eventos e gamificação',
    category: 'social',
    subcategory: 'Comunidade',
    icon: Users2,
    color: 'from-green-500 to-emerald-600',
    features: ['Fóruns temáticos', 'Sistema de eventos', 'Gamificação', 'Sistema de pontos', 'Badges'],
    techStack: ['React', 'Supabase', 'Pusher', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'dating-app',
    name: 'App de Relacionamentos',
    description: 'Plataforma de relacionamentos com matching inteligente e chat seguro',
    category: 'social',
    subcategory: 'Relacionamentos',
    icon: Heart,
    color: 'from-pink-500 to-rose-600',
    features: ['Algoritmo de matching', 'Chat com criptografia', 'Verificação de perfil', 'Sistema de likes'],
    techStack: ['React Native', 'Supabase', 'WebRTC', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias'
  },
  {
    id: 'professional-network',
    name: 'Rede Profissional',
    description: 'LinkedIn para nichos específicos com foco em networking profissional',
    category: 'social',
    subcategory: 'Networking',
    icon: Building,
    color: 'from-blue-600 to-indigo-600',
    features: ['Perfis profissionais', 'Sistema de vagas', 'Networking direcionado', 'Recomendações'],
    techStack: ['Next.js', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'crm-advanced',
    name: 'CRM Avançado',
    description: 'Sistema completo de gestão de relacionamento com clientes e automação de vendas',
    category: 'business',
    subcategory: 'CRM',
    icon: Users,
    color: 'from-purple-600 to-blue-600',
    features: ['Pipeline de vendas', 'Automação de marketing', 'Relatórios avançados', 'Integração com email'],
    techStack: ['Next.js', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'ai-project-management',
    name: 'Gestão de Projetos com IA',
    description: 'Ferramenta de gestão de projetos com inteligência artificial para otimização de recursos',
    category: 'business',
    subcategory: 'Gestão',
    icon: Brain,
    color: 'from-cyan-500 to-blue-600',
    features: ['IA para estimativas', 'Gestão de recursos', 'Análise preditiva', 'Otimização automática'],
    techStack: ['Next.js', 'Supabase', 'OpenAI', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias',
    popular: true
  },
  {
    id: 'invoice-automation',
    name: 'Automação de Faturamento',
    description: 'Sistema completo de faturamento com automação fiscal e integração bancária',
    category: 'business',
    subcategory: 'Faturamento',
    icon: Receipt,
    color: 'from-green-600 to-teal-600',
    features: ['Emissão automática de NF', 'Integração bancária', 'Cobrança automática', 'Relatórios fiscais'],
    techStack: ['Next.js', 'Supabase', 'APIs fiscais', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'telemedicine-advanced',
    name: 'Plataforma de Telemedicina',
    description: 'Sistema completo para consultas médicas online com prontuário eletrônico',
    category: 'health',
    subcategory: 'Telemedicina',
    icon: Video,
    color: 'from-blue-500 to-cyan-600',
    features: ['Consultas por vídeo', 'Prontuário eletrônico', 'Prescrição digital', 'Agendamento'],
    techStack: ['Next.js', 'Supabase', 'WebRTC', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias'
  },
  {
    id: 'fitness-monitoring',
    name: 'App de Monitoramento Fitness',
    description: 'Aplicativo completo para acompanhamento de atividades físicas e nutrição',
    category: 'health',
    subcategory: 'Fitness',
    icon: Dumbbell,
    color: 'from-orange-500 to-red-600',
    features: ['Tracking de exercícios', 'Planos nutricionais', 'Gamificação', 'Integração com wearables'],
    techStack: ['React Native', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'mental-health-platform',
    name: 'Plataforma de Saúde Mental',
    description: 'Sistema para terapia online e acompanhamento psicológico',
    category: 'health',
    subcategory: 'Saúde Mental',
    icon: Brain,
    color: 'from-purple-500 to-pink-600',
    features: ['Terapia por vídeo', 'Diário emocional', 'Exercícios de mindfulness', 'Monitoramento de humor'],
    techStack: ['React', 'Supabase', 'WebRTC', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'advanced-lms',
    name: 'LMS Avançado',
    description: 'Plataforma completa de ensino online com IA para personalização de aprendizado',
    category: 'education',
    subcategory: 'LMS',
    icon: BookOpen,
    color: 'from-indigo-500 to-purple-600',
    features: ['IA para aprendizado', 'Aulas ao vivo', 'Gamificação', 'Análise de progresso', 'Certificados'],
    techStack: ['Next.js', 'Supabase', 'OpenAI', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias',
    popular: true
  },
  {
    id: 'ai-language-app',
    name: 'App de Idiomas',
    description: 'Plataforma gamificada para aprendizado de idiomas com IA conversacional',
    category: 'education',
    subcategory: 'Idiomas',
    icon: Globe,
    color: 'from-green-500 to-blue-600',
    features: ['IA conversacional', 'Gamificação', 'Reconhecimento de voz', 'Lições adaptativas'],
    techStack: ['React Native', 'Supabase', 'Speech API', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'skills-assessment',
    name: 'Plataforma de Avaliação de Habilidades',
    description: 'Sistema para testes e certificações profissionais com proctoring online',
    category: 'education',
    subcategory: 'Avaliação',
    icon: Award,
    color: 'from-yellow-500 to-orange-600',
    features: ['Proctoring online', 'Banco de questões', 'Relatórios detalhados', 'Certificações'],
    techStack: ['Next.js', 'Supabase', 'WebRTC', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'ghost-kitchen',
    name: 'Plataforma Ghost Kitchen',
    description: 'Sistema completo para gestão de cozinhas virtuais e delivery',
    category: 'delivery',
    subcategory: 'Alimentação',
    icon: Utensils,
    color: 'from-red-500 to-orange-600',
    features: ['Múltiplas marcas', 'Gestão de cardápio', 'Otimização de entrega', 'Analytics'],
    techStack: ['Next.js', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'restaurant-reservations',
    name: 'Sistema de Reservas de Mesa',
    description: 'Plataforma para reservas de restaurantes com gestão de capacidade',
    category: 'business',
    subcategory: 'Reservas',
    icon: CalendarIcon,
    color: 'from-blue-500 to-indigo-600',
    features: ['Reservas online', 'Gestão de capacidade', 'Lista de espera', 'Notificações'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'food-waste-reduction',
    name: 'Redução de Desperdício Alimentar',
    description: 'Plataforma para conectar restaurantes com excesso de comida a consumidores',
    category: 'social',
    subcategory: 'Sustentabilidade',
    icon: Leaf,
    color: 'from-green-500 to-emerald-600',
    features: ['Ofertas em tempo real', 'Geolocalização', 'Pagamentos integrados', 'Impacto ambiental'],
    techStack: ['React', 'Supabase', 'Maps API', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'fleet-management',
    name: 'Gestão de Frota',
    description: 'Sistema completo para gerenciamento de frotas com telemetria e manutenção preditiva',
    category: 'transport',
    subcategory: 'Logística',
    icon: Truck,
    color: 'from-blue-600 to-cyan-600',
    features: ['Telemetria veicular', 'Manutenção preditiva', 'Otimização de rotas', 'Relatórios'],
    techStack: ['Next.js', 'Supabase', 'IoT APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'cargo-sharing',
    name: 'Compartilhamento de Carga',
    description: 'Plataforma para compartilhamento de espaço em cargas e otimização logística',
    category: 'transport',
    subcategory: 'Logística',
    icon: Package,
    color: 'from-orange-500 to-red-600',
    features: ['Matching de cargas', 'Otimização de rotas', 'Tracking em tempo real', 'Sistema de avaliações'],
    techStack: ['React', 'Supabase', 'Maps API', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'smart-parking',
    name: 'Gestão de Estacionamentos',
    description: 'Sistema inteligente para gestão de vagas com IoT e pagamentos automáticos',
    category: 'technology',
    subcategory: 'IoT',
    icon: Car,
    color: 'from-purple-500 to-indigo-600',
    features: ['Sensores IoT', 'Pagamento automático', 'Reserva de vagas', 'App mobile'],
    techStack: ['React Native', 'Supabase', 'IoT', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'property-management',
    name: 'Gestão de Propriedades',
    description: 'Sistema completo para gestão de imóveis, inquilinos e manutenção',
    category: 'realestate',
    subcategory: 'Gestão',
    icon: Home,
    color: 'from-green-600 to-emerald-600',
    features: ['Portal do inquilino', 'Gestão de manutenção', 'Relatórios financeiros', 'Contratos'],
    techStack: ['Next.js', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'real-estate-investment',
    name: 'Investimento Imobiliário',
    description: 'Plataforma para investimento colaborativo em imóveis com tokenização',
    category: 'finance',
    subcategory: 'Investimentos',
    icon: Building,
    color: 'from-yellow-500 to-orange-600',
    features: ['Tokenização de imóveis', 'Investimento fracionado', 'Rendimentos automáticos', 'Blockchain'],
    techStack: ['Next.js', 'Supabase', 'Web3', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias'
  },
  {
    id: 'virtual-tours',
    name: 'Tours Virtuais de Imóveis',
    description: 'Plataforma para visitas virtuais 360° e realidade aumentada',
    category: 'technology',
    subcategory: 'Realidade Virtual',
    icon: Camera,
    color: 'from-blue-500 to-purple-600',
    features: ['Tours 360°', 'Realidade aumentada', 'Agendamento virtual', 'Integração com CRM'],
    techStack: ['React', 'Three.js', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'ai-personal-assistant',
    name: 'Assistente Pessoal com IA',
    description: 'Assistente virtual inteligente para gestão de tarefas e produtividade',
    category: 'productivity',
    subcategory: 'IA',
    icon: Bot,
    color: 'from-cyan-500 to-blue-600',
    features: ['IA conversacional', 'Agendamento inteligente', 'Análise de produtividade', 'Integração com apps'],
    techStack: ['React', 'Supabase', 'OpenAI', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias',
    popular: true
  },
  {
    id: 'team-collaboration',
    name: 'Colaboração em Equipe',
    description: 'Plataforma completa para colaboração remota com whiteboard e video calls',
    category: 'productivity',
    subcategory: 'Colaboração',
    icon: Users,
    color: 'from-green-500 to-cyan-600',
    features: ['Whiteboard colaborativo', 'Video calls HD', 'Gestão de documentos', 'Chat em tempo real'],
    techStack: ['React', 'Supabase', 'WebRTC', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'ai-time-tracking',
    name: 'Controle de Tempo com IA',
    description: 'Sistema inteligente de controle de tempo com análise automática de produtividade',
    category: 'productivity',
    subcategory: 'Tempo',
    icon: Clock,
    color: 'from-purple-500 to-pink-600',
    features: ['Tracking automático', 'Análise de produtividade', 'Relatórios inteligentes', 'Insights por IA'],
    techStack: ['React', 'Supabase', 'ML APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias'
  },
  {
    id: 'streaming-platform',
    name: 'Plataforma de Streaming',
    description: 'Serviço de streaming de vídeo com recomendações por IA e conteúdo interativo',
    category: 'entertainment',
    subcategory: 'Streaming',
    icon: Video,
    color: 'from-red-500 to-pink-600',
    features: ['Streaming adaptativo', 'IA de recomendação', 'Conteúdo interativo', 'Analytics avançados'],
    techStack: ['Next.js', 'Supabase', 'CDN', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias'
  },
  {
    id: 'gaming-tournaments',
    name: 'Plataforma de Torneios Gaming',
    description: 'Sistema para organização de torneios de games com brackets e transmissões',
    category: 'entertainment',
    subcategory: 'Gaming',
    icon: Trophy,
    color: 'from-yellow-500 to-orange-600',
    features: ['Sistema de brackets', 'Transmissões ao vivo', 'Ranking global', 'Premiações'],
    techStack: ['React', 'Supabase', 'Streaming APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'virtual-events',
    name: 'Eventos Virtuais',
    description: 'Plataforma para eventos online com networking e experiências imersivas',
    category: 'entertainment',
    subcategory: 'Eventos',
    icon: Calendar,
    color: 'from-indigo-500 to-purple-600',
    features: ['Ambientes 3D', 'Networking AI', 'Stands virtuais', 'Interação em tempo real'],
    techStack: ['React', 'Three.js', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias'
  },
  {
    id: 'whatsapp-ecommerce-bot',
    name: 'Bot E-commerce WhatsApp',
    description: 'Bot inteligente para vendas via WhatsApp com catálogo integrado e pagamentos',
    category: 'social',
    subcategory: 'E-commerce',
    icon: ShoppingBag,
    color: 'from-green-500 to-emerald-600',
    features: ['Catálogo de produtos', 'Carrinho de compras', 'Pagamentos PIX', 'Checkout automático', 'Suporte ao cliente'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase', 'Stripe'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias',
    popular: true
  },
  {
    id: 'whatsapp-restaurant-bot',
    name: 'Bot Restaurante WhatsApp',
    description: 'Assistente virtual para restaurantes com cardápio digital e pedidos automatizados',
    category: 'food',
    subcategory: 'Alimentação',
    icon: Utensils,
    color: 'from-orange-500 to-red-600',
    features: ['Cardápio interativo', 'Pedidos automatizados', 'Delivery tracking', 'Sistema de avaliações'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'whatsapp-appointment-bot',
    name: 'Bot Agendamento WhatsApp',
    description: 'Bot para agendamento de consultas e serviços com calendário integrado',
    category: 'social',
    subcategory: 'Agendamento',
    icon: Calendar,
    color: 'from-blue-500 to-cyan-600',
    features: ['Agendamento inteligente', 'Lembretes automáticos', 'Reagendamento fácil', 'Integração com calendário'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'whatsapp-support-bot',
    name: 'Bot Suporte WhatsApp',
    description: 'Bot de atendimento ao cliente com IA para respostas inteligentes e escalação',
    category: 'social',
    subcategory: 'Suporte',
    icon: MessageCircle,
    color: 'from-purple-500 to-indigo-600',
    features: ['IA conversacional', 'Base de conhecimento', 'Escalação para humanos', 'Histórico de conversas'],
    techStack: ['Node.js', 'OpenAI', 'WhatsApp API', 'Supabase'],
    difficulty: 'advanced',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'whatsapp-education-bot',
    name: 'Bot Educacional WhatsApp',
    description: 'Assistente educacional para cursos online com quizzes e acompanhamento de progresso',
    category: 'social',
    subcategory: 'Educação',
    icon: BookOpen,
    color: 'from-green-500 to-blue-600',
    features: ['Conteúdo interativo', 'Quizzes automáticos', 'Progresso personalizado', 'Certificados'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'whatsapp-health-bot',
    name: 'Bot Saúde WhatsApp',
    description: 'Assistente de saúde para lembretes de medicamentos e triagem inicial',
    category: 'social',
    subcategory: 'Saúde',
    icon: Heart,
    color: 'from-red-500 to-pink-600',
    features: ['Lembretes de medicação', 'Triagem de sintomas', 'Agendamento médico', 'Histórico de saúde'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'whatsapp-realestate-bot',
    name: 'Bot Imóveis WhatsApp',
    description: 'Bot para imobiliárias com busca inteligente de imóveis e agendamento de visitas',
    category: 'social',
    subcategory: 'Imóveis',
    icon: Home,
    color: 'from-blue-600 to-indigo-600',
    features: ['Busca por critérios', 'Galeria de fotos', 'Agendamento de visitas', 'Filtros avançados'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'whatsapp-finance-bot',
    name: 'Bot Financeiro WhatsApp',
    description: 'Assistente financeiro para controle de gastos e investimentos via WhatsApp',
    category: 'social',
    subcategory: 'Finanças',
    icon: Wallet,
    color: 'from-yellow-500 to-orange-600',
    features: ['Controle de gastos', 'Análise financeira', 'Dicas de investimento', 'Relatórios automáticos'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'whatsapp-hr-bot',
    name: 'Bot RH WhatsApp',
    description: 'Bot para recursos humanos com gestão de colaboradores e processos internos',
    category: 'social',
    subcategory: 'RH',
    icon: Users,
    color: 'from-purple-600 to-blue-600',
    features: ['Gestão de folha de ponto', 'Solicitações de férias', 'Onboarding digital', 'Comunicados internos'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'whatsapp-delivery-bot',
    name: 'Bot Delivery WhatsApp',
    description: 'Bot para serviços de delivery com tracking em tempo real e otimização de rotas',
    category: 'social',
    subcategory: 'Delivery',
    icon: Truck,
    color: 'from-green-600 to-cyan-600',
    features: ['Tracking em tempo real', 'Otimização de rotas', 'Notificações automáticas', 'Status do pedido'],
    techStack: ['Node.js', 'WhatsApp API', 'Maps API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'whatsapp-pharmacy-bot',
    name: 'Bot Farmácia WhatsApp',
    description: 'Assistente para farmácias com consulta de medicamentos e delivery',
    category: 'social',
    subcategory: 'Farmácia',
    icon: Pill,
    color: 'from-blue-500 to-green-600',
    features: ['Consulta de medicamentos', 'Receitas digitais', 'Delivery farmácia', 'Controle de estoque'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'whatsapp-automotive-bot',
    name: 'Bot Automotivo WhatsApp',
    description: 'Bot para concessionárias e oficinas com agendamento e orçamentos',
    category: 'social',
    subcategory: 'Automotivo',
    icon: Car,
    color: 'from-gray-600 to-blue-600',
    features: ['Agendamento de serviços', 'Orçamentos automáticos', 'Histórico do veículo', 'Lembretes de revisão'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'whatsapp-beauty-bot',
    name: 'Bot Beleza WhatsApp',
    description: 'Assistente para salões de beleza com agendamento e consultas de tratamentos',
    category: 'social',
    subcategory: 'Beleza',
    icon: Sparkles,
    color: 'from-pink-500 to-purple-600',
    features: ['Agendamento de serviços', 'Consulta de tratamentos', 'Programa de fidelidade', 'Lembretes'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'whatsapp-travel-bot',
    name: 'Bot Viagem WhatsApp',
    description: 'Assistente de viagens com pesquisa de destinos e reservas automatizadas',
    category: 'social',
    subcategory: 'Viagens',
    icon: Plane,
    color: 'from-cyan-500 to-blue-600',
    features: ['Pesquisa de destinos', 'Reservas automáticas', 'Itinerários personalizados', 'Dicas de viagem'],
    techStack: ['Node.js', 'WhatsApp API', 'Travel APIs', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'whatsapp-petcare-bot',
    name: 'Bot Pet Care WhatsApp',
    description: 'Assistente para pet shops e veterinárias com agendamento e cuidados',
    category: 'social',
    subcategory: 'Pet Care',
    icon: Dog,
    color: 'from-orange-500 to-yellow-600',
    features: ['Agendamento veterinário', 'Lembretes de vacina', 'Dicas de cuidados', 'Histórico do pet'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'whatsapp-legal-bot',
    name: 'Bot Jurídico WhatsApp',
    description: 'Assistente jurídico com consultas automatizadas e agendamento de advogados',
    category: 'social',
    subcategory: 'Jurídico',
    icon: Shield,
    color: 'from-gray-700 to-blue-700',
    features: ['Consultas jurídicas', 'Documentos automáticos', 'Agendamento de advogados', 'Base legal'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'advanced',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'whatsapp-fitness-bot',
    name: 'Bot Fitness WhatsApp',
    description: 'Personal trainer virtual com treinos personalizados e acompanhamento nutricional',
    category: 'social',
    subcategory: 'Fitness',
    icon: Dumbbell,
    color: 'from-red-500 to-orange-600',
    features: ['Treinos personalizados', 'Acompanhamento nutricional', 'Motivação diária', 'Progresso fitness'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'whatsapp-insurance-bot',
    name: 'Bot Seguros WhatsApp',
    description: 'Assistente para seguradoras com cotações automáticas e sinistros',
    category: 'social',
    subcategory: 'Seguros',
    icon: Shield,
    color: 'from-blue-700 to-indigo-700',
    features: ['Cotações automáticas', 'Abertura de sinistros', 'Acompanhamento de processos', 'Renovações'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'whatsapp-banking-bot',
    name: 'Bot Bancário WhatsApp',
    description: 'Assistente bancário com consultas de saldo, transferências e investimentos',
    category: 'social',
    subcategory: 'Bancário',
    icon: CreditCard,
    color: 'from-green-700 to-blue-700',
    features: ['Consulta de saldo', 'Transferências seguras', 'Investimentos automáticos', 'Extrato digital'],
    techStack: ['Node.js', 'WhatsApp API', 'Banking APIs', 'Supabase'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'whatsapp-agriculture-bot',
    name: 'Bot Agricultura WhatsApp',
    description: 'Assistente para produtores rurais com monitoramento de cultivos e clima',
    category: 'social',
    subcategory: 'Agricultura',
    icon: Sprout,
    color: 'from-green-600 to-emerald-600',
    features: ['Monitoramento de cultivos', 'Previsão do tempo', 'Dicas de plantio', 'Mercado agrícola'],
    techStack: ['Node.js', 'WhatsApp API', 'Weather APIs', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'email-marketing-platform',
    name: 'Email Marketing',
    description: 'Plataforma de campanhas por email',
    category: 'marketing',
    subcategory: 'Email',
    icon: Mail,
    color: 'from-blue-500 to-purple-600',
    features: ['Templates', 'Automação', 'Segmentação', 'Analytics'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'social-media-manager',
    name: 'Gerenciador de Redes Sociais',
    description: 'Gestão unificada de redes sociais',
    category: 'marketing',
    subcategory: 'Social Media',
    icon: Share,
    color: 'from-pink-500 to-red-600',
    features: ['Agendamento', 'Analytics', 'Múltiplas Contas', 'Relatórios'],
    techStack: ['Next.js', 'Supabase', 'Social APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-7 dias'
  },
  {
    id: 'landing-page-builder',
    name: 'Criador de Landing Pages',
    description: 'Construtor de páginas de conversão',
    category: 'marketing',
    subcategory: 'Landing Pages',
    icon: Monitor,
    color: 'from-yellow-500 to-orange-600',
    features: ['Drag & Drop', 'Templates', 'A/B Testing', 'Conversão'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'personal-finance-tracker',
    name: 'Finanças Pessoais',
    description: 'Controle completo das finanças pessoais',
    category: 'finance',
    subcategory: 'Pessoal',
    icon: Wallet,
    color: 'from-green-500 to-emerald-600',
    features: ['Orçamento', 'Categorização', 'Metas', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'investment-platform',
    name: 'Plataforma de Investimentos',
    description: 'Gestão de carteira de investimentos',
    category: 'finance',
    subcategory: 'Investimentos',
    icon: TrendingUp,
    color: 'from-blue-600 to-cyan-600',
    features: ['Portfolio', 'Análise', 'Rebalanceamento', 'ROI'],
    techStack: ['Next.js', 'Supabase', 'Finance APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'expense-tracker',
    name: 'Rastreador de Gastos',
    description: 'Acompanhamento detalhado de despesas',
    category: 'finance',
    subcategory: 'Gastos',
    icon: Calculator,
    color: 'from-red-500 to-pink-600',
    features: ['Câmera de Recibos', 'Categorias', 'Limite de Gastos', 'Alertas'],
    techStack: ['React Native', 'Supabase', 'OCR', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'api-gateway',
    name: 'Gateway de APIs',
    description: 'Gestão centralizada de APIs',
    category: 'technology',
    subcategory: 'APIs',
    icon: Network,
    color: 'from-gray-600 to-blue-600',
    features: ['Rate Limiting', 'Autenticação', 'Monitoramento', 'Analytics'],
    techStack: ['Node.js', 'Supabase', 'Redis'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'monitoring-platform',
    name: 'Plataforma de Monitoramento',
    description: 'Monitoramento de infraestrutura e aplicações',
    category: 'technology',
    subcategory: 'Monitoramento',
    icon: Gauge,
    color: 'from-orange-500 to-red-600',
    features: ['Métricas', 'Alertas', 'Logs', 'Dashboards'],
    techStack: ['React', 'Supabase', 'Grafana', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'cicd-pipeline',
    name: 'Pipeline CI/CD',
    description: 'Integração e entrega contínua',
    category: 'technology',
    subcategory: 'DevOps',
    icon: GitBranch,
    color: 'from-purple-600 to-indigo-600',
    features: ['Build Automático', 'Testes', 'Deploy', 'Rollback'],
    techStack: ['Node.js', 'Docker', 'GitHub Actions'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias'
  },
  {
    id: 'cloud-storage',
    name: 'Armazenamento em Nuvem',
    description: 'Solução de storage escalável',
    category: 'technology',
    subcategory: 'Storage',
    icon: HardDrive,
    color: 'from-blue-500 to-cyan-600',
    features: ['Backup', 'Sincronização', 'Compartilhamento', 'Versionamento'],
    techStack: ['React', 'Supabase Storage', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'food-delivery-platform',
    name: 'Delivery de Comida',
    description: 'Plataforma completa para delivery de alimentos',
    category: 'delivery',
    subcategory: 'Alimentação',
    icon: Pizza,
    color: 'from-red-500 to-orange-600',
    features: ['Cardápio Digital', 'Pedidos Online', 'Rastreamento', 'Avaliações'],
    techStack: ['React Native', 'Supabase', 'Maps API', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias',
    popular: true
  },
  {
    id: 'grocery-delivery',
    name: 'Supermercado Online',
    description: 'Entrega de produtos de supermercado',
    category: 'delivery',
    subcategory: 'Supermercado',
    icon: ShoppingCart,
    color: 'from-green-500 to-emerald-600',
    features: ['Catálogo', 'Lista de Compras', 'Agendamento', 'Promoções'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'pharmacy-delivery-advanced',
    name: 'Farmácia Delivery',
    description: 'Entrega de medicamentos',
    category: 'delivery',
    subcategory: 'Farmácia',
    icon: Pill,
    color: 'from-blue-500 to-cyan-600',
    features: ['Receita Digital', 'Estoque', 'Entrega Expressa', 'Controle medicamentos'],
    techStack: ['React', 'Supabase', 'OCR', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias'
  },

  // PDV & Vendas
  {
    id: 'cloud-pdv',
    name: 'Sistema de PDV em Nuvem',
    description: 'Sistema completo de ponto de venda na nuvem com recursos avançados',
    category: 'pdv-sales',
    subcategory: 'PDV',
    icon: CreditCard,
    color: 'from-blue-500 to-purple-600',
    features: ['Vendas por QR Code', 'Nota fiscal integrada', 'Integração com maquininhas', 'Checkout móvel'],
    techStack: ['React', 'Supabase', 'Payment APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias',
    popular: true
  },
  {
    id: 'commission-panel',
    name: 'Painel de Comissão por Vendedor',
    description: 'Sistema de controle de comissões e metas por vendedor',
    category: 'pdv-sales',
    subcategory: 'Comissões',
    icon: TrendingUp,
    color: 'from-green-500 to-emerald-600',
    features: ['Cálculo automático', 'Metas por vendedor', 'Relatórios', 'Ranking'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'abandoned-cart-recovery',
    name: 'Recuperação de Carrinho Abandonado',
    description: 'Sistema de recuperação via WhatsApp para vendas não finalizadas',
    category: 'pdv-sales',
    subcategory: 'Recuperação',
    icon: MessageCircle,
    color: 'from-orange-500 to-red-600',
    features: ['Automação WhatsApp', 'Lembretes personalizados', 'Analytics', 'Conversão'],
    techStack: ['Node.js', 'WhatsApp API', 'Supabase'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'self-service-app',
    name: 'App de Autoatendimento',
    description: 'Aplicativo para clientes fazerem pedidos sem atendimento',
    category: 'pdv-sales',
    subcategory: 'Autoatendimento',
    icon: Smartphone,
    color: 'from-purple-500 to-pink-600',
    features: ['Cardápio digital', 'Pedidos diretos', 'Pagamento integrado', 'QR Code'],
    techStack: ['React Native', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },

  // Gestão de Estoque
  {
    id: 'barcode-inventory',
    name: 'Inventário com Código de Barras',
    description: 'Sistema de inventário com leitura por código de barras',
    category: 'stock',
    subcategory: 'Inventário',
    icon: QrCode,
    color: 'from-blue-500 to-cyan-600',
    features: ['Leitura por câmera', 'Contagem automática', 'Relatórios de divergência', 'Etiquetas'],
    techStack: ['React Native', 'Supabase', 'Barcode Scanner', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'stock-alerts',
    name: 'Alertas de Estoque Mínimo',
    description: 'Sistema de alertas e reposição automática de produtos',
    category: 'stock',
    subcategory: 'Alertas',
    icon: Bell,
    color: 'from-red-500 to-orange-600',
    features: ['Alertas automáticos', 'Previsão de demanda', 'Sugestão de compra', 'Notificações'],
    techStack: ['React', 'Supabase', 'Push Notifications', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'abc-curve',
    name: 'Curva ABC de Produtos',
    description: 'Análise de produtos por importância e rentabilidade',
    category: 'stock',
    subcategory: 'Análise',
    icon: BarChart,
    color: 'from-green-500 to-blue-600',
    features: ['Classificação ABC', 'Gráficos de performance', 'Relatórios', 'Insights'],
    techStack: ['React', 'Supabase', 'Charts.js', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'multi-warehouse',
    name: 'Multiarmazém com Transferência',
    description: 'Gestão de múltiplos armazéns com transferência entre lojas',
    category: 'stock',
    subcategory: 'Multiarmazém',
    icon: Warehouse,
    color: 'from-purple-500 to-indigo-600',
    features: ['Múltiplos locais', 'Transferências', 'Rastreamento', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias'
  },

  // Financeiro e Cobrança
  {
    id: 'automated-cashflow',
    name: 'Fluxo de Caixa Automatizado',
    description: 'Sistema automatizado de controle de fluxo de caixa',
    category: 'financial',
    subcategory: 'Fluxo de Caixa',
    icon: TrendingUp,
    color: 'from-green-500 to-emerald-600',
    features: ['Projeções automáticas', 'Categorização', 'Alertas', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Charts.js', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'bank-reconciliation',
    name: 'Conciliação Bancária Automática',
    description: 'Conciliação automática de extratos bancários',
    category: 'financial',
    subcategory: 'Conciliação',
    icon: CreditCard,
    color: 'from-blue-500 to-purple-600',
    features: ['Import de extratos', 'Matching automático', 'Divergências', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Bank APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'recurring-billing',
    name: 'Sistema de Boletos Recorrentes',
    description: 'Geração automática de boletos com cobrança recorrente',
    category: 'financial',
    subcategory: 'Cobrança',
    icon: Receipt,
    color: 'from-yellow-500 to-orange-600',
    features: ['Geração automática', 'Vencimentos', 'Juros e multa', 'Baixa automática'],
    techStack: ['React', 'Supabase', 'Payment APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias'
  },
  {
    id: 'pix-qr-billing',
    name: 'Cobrança via PIX com QR Code',
    description: 'Sistema de cobrança com QR Code dinâmico PIX',
    category: 'financial',
    subcategory: 'PIX',
    icon: QrCode,
    color: 'from-green-600 to-teal-600',
    features: ['QR Code dinâmico', 'Cobrança instantânea', 'Webhook', 'Conciliação'],
    techStack: ['React', 'Supabase', 'PIX APIs', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },

  // Bares, Restaurantes e Delivery
  {
    id: 'qr-table-orders',
    name: 'Sistema de Pedidos por QR Code',
    description: 'Pedidos diretos da mesa via QR Code sem garçom',
    category: 'restaurant',
    subcategory: 'Pedidos',
    icon: QrCode,
    color: 'from-orange-500 to-red-600',
    features: ['Cardápio digital', 'Pedidos da mesa', 'Pagamento integrado', 'Status em tempo real'],
    techStack: ['React', 'Supabase', 'Payment APIs', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias',
    popular: true
  },
  {
    id: 'digital-menu',
    name: 'Cardápio Digital com Fotos',
    description: 'Cardápio digital interativo com fotos e descrições',
    category: 'restaurant',
    subcategory: 'Cardápio',
    icon: Image,
    color: 'from-blue-500 to-cyan-600',
    features: ['Upload de fotos', 'Descrições detalhadas', 'Preços dinâmicos', 'Categorias'],
    techStack: ['React', 'Supabase Storage', 'Tailwind'],
    difficulty: 'beginner',
    estimatedTime: '2-3 dias'
  },
  {
    id: 'electronic-bill',
    name: 'Comanda Eletrônica',
    description: 'Sistema digital de comandas para bares e restaurantes',
    category: 'restaurant',
    subcategory: 'Comanda',
    icon: FileText,
    color: 'from-purple-500 to-pink-600',
    features: ['Comandas digitais', 'Controle de consumo', 'Divisão de conta', 'Histórico'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'delivery-router',
    name: 'Roteirizador para Entregadores',
    description: 'Otimização de rotas para entregadores de delivery',
    category: 'restaurant',
    subcategory: 'Delivery',
    icon: MapPin,
    color: 'from-green-500 to-emerald-600',
    features: ['Otimização de rotas', 'GPS integrado', 'Múltiplas entregas', 'Tempo estimado'],
    techStack: ['React Native', 'Maps API', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias'
  },

  // CRM e Relacionamento
  {
    id: 'birthday-campaigns',
    name: 'Cadastro com Aniversários',
    description: 'CRM com campanhas automáticas de aniversário',
    category: 'crm',
    subcategory: 'Campanhas',
    icon: Calendar,
    color: 'from-pink-500 to-red-600',
    features: ['Campanhas automáticas', 'WhatsApp/SMS/Email', 'Cupons personalizados', 'Histórico'],
    techStack: ['React', 'Supabase', 'Communication APIs', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'customer-scoring',
    name: 'Score de Fidelidade por Consumo',
    description: 'Sistema de pontuação baseado no consumo do cliente',
    category: 'crm',
    subcategory: 'Fidelidade',
    icon: Star,
    color: 'from-yellow-500 to-orange-600',
    features: ['Sistema de pontos', 'Níveis de fidelidade', 'Recompensas', 'Gamificação'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'referral-program',
    name: 'Programa de Indicações',
    description: 'Sistema de indicações com recompensas automáticas',
    category: 'crm',
    subcategory: 'Indicações',
    icon: Users,
    color: 'from-green-500 to-blue-600',
    features: ['Códigos de indicação', 'Tracking de conversões', 'Recompensas automáticas', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'social-integration',
    name: 'Integração com Redes Sociais',
    description: 'Integração com Instagram, WhatsApp e Facebook',
    category: 'crm',
    subcategory: 'Social',
    icon: Share,
    color: 'from-purple-500 to-pink-600',
    features: ['Multi-canal', 'Histórico unificado', 'Automação', 'Analytics'],
    techStack: ['React', 'Social APIs', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },

  // Gestão de Funcionários
  {
    id: 'online-schedule',
    name: 'Escala de Trabalho Online',
    description: 'Sistema online para criação e gestão de escalas',
    category: 'employees',
    subcategory: 'Escala',
    icon: Calendar,
    color: 'from-blue-500 to-cyan-600',
    features: ['Escalas automáticas', 'Troca de turnos', 'Notificações', 'Aprovações'],
    techStack: ['React', 'Supabase', 'Push Notifications', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'geo-timetracking',
    name: 'Controle de Ponto por Geolocalização',
    description: 'Sistema de ponto eletrônico com validação por GPS',
    category: 'employees',
    subcategory: 'Ponto',
    icon: MapPin,
    color: 'from-green-500 to-emerald-600',
    features: ['GPS tracking', 'Validação por local', 'Relatórios', 'Fotos obrigatórias'],
    techStack: ['React Native', 'Supabase', 'GPS APIs', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'performance-evaluation',
    name: 'Avaliação de Desempenho',
    description: 'Sistema de avaliação 360° para funcionários',
    category: 'employees',
    subcategory: 'Avaliação',
    icon: Star,
    color: 'from-yellow-500 to-orange-600',
    features: ['Avaliação 360°', 'Metas individuais', 'Feedback contínuo', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'digital-onboarding',
    name: 'Treinamentos e Documentos Digitais',
    description: 'Portal de treinamento e documentos para funcionários',
    category: 'employees',
    subcategory: 'Treinamento',
    icon: BookOpen,
    color: 'from-purple-500 to-indigo-600',
    features: ['Cursos online', 'Documentos digitais', 'Progresso tracking', 'Certificados'],
    techStack: ['React', 'Supabase', 'Video Streaming', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },

  // Notas Fiscais e Regulatório
  {
    id: 'automated-nfe',
    name: 'Emissão de NFe/NFCe Automática',
    description: 'Sistema automatizado de emissão de notas fiscais',
    category: 'fiscal',
    subcategory: 'Notas Fiscais',
    icon: FileText,
    color: 'from-blue-500 to-purple-600',
    features: ['Emissão automática', 'Validação XML', 'DANFE', 'Contingência'],
    techStack: ['React', 'Fiscal APIs', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'accounting-reports',
    name: 'Relatórios para Contabilidade',
    description: 'Geração automática de relatórios contábeis',
    category: 'fiscal',
    subcategory: 'Contabilidade',
    icon: BarChart,
    color: 'from-green-500 to-emerald-600',
    features: ['DRE automática', 'Balancete', 'Livro caixa', 'Exportação'],
    techStack: ['React', 'Supabase', 'PDF Generation', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'license-monitoring',
    name: 'Monitoramento de Alvarás',
    description: 'Controle de vencimento de licenças e alvarás',
    category: 'fiscal',
    subcategory: 'Licenças',
    icon: Shield,
    color: 'from-red-500 to-orange-600',
    features: ['Calendário de vencimentos', 'Alertas automáticos', 'Documentos digitais', 'Renovações'],
    techStack: ['React', 'Supabase', 'Notifications', 'Tailwind'],
    difficulty: 'beginner',
    estimatedTime: '2-3 dias'
  },
  {
    id: 'tax-calculator',
    name: 'Cálculo Automático de Tributos',
    description: 'Calculadora automática de impostos por estado',
    category: 'fiscal',
    subcategory: 'Tributos',
    icon: Calculator,
    color: 'from-yellow-500 to-orange-600',
    features: ['Cálculo por estado', 'Regras atualizadas', 'Simulações', 'Relatórios'],
    techStack: ['React', 'Tax APIs', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },

  // Assistência Técnica
  {
    id: 'service-orders',
    name: 'Geração de Ordens de Serviço',
    description: 'Sistema completo de ordens de serviço online',
    category: 'service',
    subcategory: 'OS',
    icon: Wrench,
    color: 'from-blue-500 to-cyan-600',
    features: ['OS digitais', 'Checklist customizado', 'Fotos e anexos', 'Assinatura digital'],
    techStack: ['React', 'Supabase', 'Digital Signature', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'technical-visits',
    name: 'Agendamento de Visitas Técnicas',
    description: 'Sistema de agendamento para técnicos de campo',
    category: 'service',
    subcategory: 'Agendamento',
    icon: Calendar,
    color: 'from-green-500 to-emerald-600',
    features: ['Agenda técnicos', 'GPS routing', 'Notificações', 'Histórico'],
    techStack: ['React Native', 'Supabase', 'Maps API', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'equipment-history',
    name: 'Histórico por Equipamento',
    description: 'Registro completo de manutenções por equipamento',
    category: 'service',
    subcategory: 'Histórico',
    icon: Database,
    color: 'from-purple-500 to-indigo-600',
    features: ['QR Code por equipamento', 'Histórico completo', 'Manutenções preventivas', 'Relatórios'],
    techStack: ['React', 'Supabase', 'QR Generator', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'warranty-system',
    name: 'Sistema de Garantia por OS',
    description: 'Controle automático de garantias por ordem de serviço',
    category: 'service',
    subcategory: 'Garantia',
    icon: Shield,
    color: 'from-yellow-500 to-orange-600',
    features: ['Garantias automáticas', 'Vencimentos', 'Histórico', 'Certificados'],
    techStack: ['React', 'Supabase', 'PDF Generation', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },

  // Beleza & Saúde
  {
    id: 'online-booking',
    name: 'Agenda Online com Confirmação',
    description: 'Sistema de agendamento com confirmação automática',
    category: 'beauty',
    subcategory: 'Agendamento',
    icon: Calendar,
    color: 'from-pink-500 to-purple-600',
    features: ['Agendamento online', 'Confirmação WhatsApp', 'Lista de espera', 'Reagendamento'],
    techStack: ['React', 'Supabase', 'WhatsApp API', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias',
    popular: true
  },
  {
    id: 'session-packages',
    name: 'Pacotes de Sessões',
    description: 'Controle de pacotes de sessões com uso automático',
    category: 'beauty',
    subcategory: 'Pacotes',
    icon: Package,
    color: 'from-blue-500 to-cyan-600',
    features: ['Pacotes personalizados', 'Controle de uso', 'Validade', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'digital-record',
    name: 'Prontuário Digital do Cliente',
    description: 'Prontuário eletrônico para clínicas e salões',
    category: 'beauty',
    subcategory: 'Prontuário',
    icon: FileText,
    color: 'from-green-500 to-emerald-600',
    features: ['Histórico completo', 'Fotos antes/depois', 'Observações', 'Evolução'],
    techStack: ['React', 'Supabase Storage', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'commission-control',
    name: 'Controle de Comissões',
    description: 'Sistema de comissões por agendamento e profissional',
    category: 'beauty',
    subcategory: 'Comissão',
    icon: TrendingUp,
    color: 'from-yellow-500 to-orange-600',
    features: ['Cálculo automático', 'Por profissional', 'Metas', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },

  // Imóveis
  {
    id: 'contract-management',
    name: 'Gestão de Contratos com Vencimentos',
    description: 'Sistema completo de gestão de contratos de aluguel',
    category: 'real-estate',
    subcategory: 'Contratos',
    icon: FileText,
    color: 'from-blue-500 to-indigo-600',
    features: ['Contratos digitais', 'Vencimentos automáticos', 'Reajustes', 'Renovações'],
    techStack: ['React', 'Supabase', 'Digital Signature', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '5-6 dias'
  },
  {
    id: 'rent-billing',
    name: 'Geração Automática de Boletos',
    description: 'Sistema automatizado de cobrança de aluguel',
    category: 'real-estate',
    subcategory: 'Cobrança',
    icon: Receipt,
    color: 'from-green-500 to-emerald-600',
    features: ['Boletos automáticos', 'Multa e juros', 'PIX integrado', 'Baixa automática'],
    techStack: ['React', 'Supabase', 'Payment APIs', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'property-visits',
    name: 'Plataforma de Visitas Agendadas',
    description: 'Sistema de agendamento de visitas a imóveis',
    category: 'real-estate',
    subcategory: 'Visitas',
    icon: Home,
    color: 'from-purple-500 to-pink-600',
    features: ['Agendamento online', 'Disponibilidade', 'Confirmações', 'Feedback'],
    techStack: ['React', 'Supabase', 'Calendar API', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'property-comparison',
    name: 'Comparativo de Imóveis por Bairro',
    description: 'Sistema de análise comparativa de valores por região',
    category: 'real-estate',
    subcategory: 'Análise',
    icon: BarChart,
    color: 'from-yellow-500 to-orange-600',
    features: ['Comparativos automáticos', 'Mapas de calor', 'Relatórios', 'Tendências'],
    techStack: ['React', 'Maps API', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias'
  },

  // Academias
  {
    id: 'gym-access-control',
    name: 'Controle de Planos e Vencimentos',
    description: 'Sistema completo de gestão de academias',
    category: 'gym',
    subcategory: 'Gestão',
    icon: CreditCard,
    color: 'from-blue-500 to-purple-600',
    features: ['Planos personalizados', 'Acesso por QR/biometria', 'Cobrança automática', 'App do aluno'],
    techStack: ['React Native', 'Supabase', 'Biometric APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'digital-workout',
    name: 'Ficha de Treino Digital',
    description: 'Sistema digital de fichas de treino personalizadas',
    category: 'gym',
    subcategory: 'Treino',
    icon: Dumbbell,
    color: 'from-orange-500 to-red-600',
    features: ['Fichas personalizadas', 'Vídeos de exercícios', 'Progresso tracking', 'Evolução'],
    techStack: ['React Native', 'Supabase', 'Video Streaming', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'class-management',
    name: 'Gestão de Turmas e Horários',
    description: 'Sistema de aulas coletivas com agendamento',
    category: 'gym',
    subcategory: 'Aulas',
    icon: Users,
    color: 'from-green-500 to-emerald-600',
    features: ['Agendamento de aulas', 'Capacidade máxima', 'Lista de espera', 'Avaliações'],
    techStack: ['React', 'Supabase', 'Calendar API', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },
  {
    id: 'physical-assessment',
    name: 'Avaliação Física com Gráficos',
    description: 'Sistema de avaliação física com evolução gráfica',
    category: 'gym',
    subcategory: 'Avaliação',
    icon: Activity,
    color: 'from-purple-500 to-pink-600',
    features: ['Medidas corporais', 'Gráficos de evolução', 'Fotos comparativas', 'Relatórios'],
    techStack: ['React', 'Supabase', 'Charts.js', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },

  // Inteligência Artificial
  {
    id: 'demand-prediction',
    name: 'Previsão de Demanda por Produto',
    description: 'IA para prever demanda e otimizar estoque',
    category: 'ai',
    subcategory: 'Previsão',
    icon: Brain,
    color: 'from-cyan-500 to-blue-600',
    features: ['Machine Learning', 'Análise histórica', 'Sazonalidade', 'Otimização'],
    techStack: ['Python', 'Supabase', 'ML APIs', 'React'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias',
    popular: true
  },
  {
    id: 'auto-descriptions',
    name: 'Geração Automática de Descrições',
    description: 'IA para gerar descrições de produtos automaticamente',
    category: 'ai',
    subcategory: 'Conteúdo',
    icon: FileText,
    color: 'from-green-500 to-emerald-600',
    features: ['GPT integrado', 'Descrições otimizadas', 'SEO friendly', 'Múltiplos idiomas'],
    techStack: ['React', 'OpenAI API', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'customer-classification',
    name: 'Classificação Automática de Clientes',
    description: 'IA para segmentar clientes automaticamente',
    category: 'ai',
    subcategory: 'Segmentação',
    icon: Users,
    color: 'from-purple-500 to-pink-600',
    features: ['Segmentação inteligente', 'Perfis automáticos', 'Campanhas direcionadas', 'Analytics'],
    techStack: ['React', 'ML APIs', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'chatbot-trained',
    name: 'Chatbot Treinado com Produtos',
    description: 'Chatbot com IA treinado na base de produtos da loja',
    category: 'ai',
    subcategory: 'Chatbot',
    icon: Bot,
    color: 'from-blue-500 to-cyan-600',
    features: ['IA conversacional', 'Base de conhecimento', 'Integração WhatsApp', 'Aprendizado contínuo'],
    techStack: ['Node.js', 'OpenAI', 'WhatsApp API', 'Supabase'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },

  // Setores Específicos - Pet Shops
  {
    id: 'pet-grooming',
    name: 'Agendamento de Banho e Tosa',
    description: 'Sistema especializado para pet shops com serviços',
    category: 'specific',
    subcategory: 'Pet Shop',
    icon: Dog,
    color: 'from-orange-500 to-yellow-600',
    features: ['Agendamento por pet', 'Histórico de serviços', 'Fotos antes/depois', 'Lembretes'],
    techStack: ['React', 'Supabase', 'Image Storage', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'pet-vaccination',
    name: 'Carteirinha de Vacinação Digital',
    description: 'Carteirinha digital de vacinação para pets',
    category: 'specific',
    subcategory: 'Pet Shop',
    icon: Heart,
    color: 'from-blue-500 to-green-600',
    features: ['Carteirinha digital', 'Histórico completo', 'Lembretes automáticos', 'QR Code'],
    techStack: ['React Native', 'Supabase', 'QR Generator', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },

  // Setores Específicos - Farmácias
  {
    id: 'controlled-drugs',
    name: 'Controle de Medicamentos Controlados',
    description: 'Sistema especializado para farmácias com medicamentos controlados',
    category: 'specific',
    subcategory: 'Farmácia',
    icon: Pill,
    color: 'from-red-500 to-orange-600',
    features: ['Receitas obrigatórias', 'Relatórios ANVISA', 'Estoque controlado', 'Rastreabilidade'],
    techStack: ['React', 'Supabase', 'OCR', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'health-surveillance',
    name: 'Relatório para Vigilância Sanitária',
    description: 'Geração automática de relatórios para órgãos de controle',
    category: 'specific',
    subcategory: 'Farmácia',
    icon: Shield,
    color: 'from-blue-500 to-purple-600',
    features: ['Relatórios automáticos', 'Compliance', 'Auditoria', 'Exportação'],
    techStack: ['React', 'Supabase', 'PDF Generation', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias'
  },

  // Setores Específicos - Oficinas
  {
    id: 'vehicle-budget',
    name: 'Orçamento por Peça e Mão de Obra',
    description: 'Sistema especializado para oficinas mecânicas',
    category: 'specific',
    subcategory: 'Oficina',
    icon: Wrench,
    color: 'from-gray-600 to-blue-600',
    features: ['Orçamentos detalhados', 'Catálogo de peças', 'Mão de obra', 'Aprovação digital'],
    techStack: ['React', 'Supabase', 'Digital Signature', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'vehicle-history',
    name: 'Histórico por Veículo',
    description: 'Histórico completo de manutenções por veículo',
    category: 'specific',
    subcategory: 'Oficina',
    icon: Car,
    color: 'from-green-500 to-emerald-600',
    features: ['Histórico por placa', 'Manutenções preventivas', 'Peças trocadas', 'Garantias'],
    techStack: ['React', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },

  // Ideias Inovadoras
  {
    id: 'hourly-equipment-rental',
    name: 'Aluguel de Equipamentos por Hora',
    description: 'Plataforma inovadora para aluguel por hora',
    category: 'innovative',
    subcategory: 'Aluguel',
    icon: Clock,
    color: 'from-purple-500 to-pink-600',
    features: ['Reserva por hora', 'Pagamento automático', 'Disponibilidade real-time', 'GPS tracking'],
    techStack: ['React Native', 'Supabase', 'Payment APIs', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '6-8 dias'
  },
  {
    id: 'food-truck-management',
    name: 'Gestão de Food Trucks',
    description: 'Sistema com geolocalização para food trucks',
    category: 'innovative',
    subcategory: 'Food Truck',
    icon: Truck,
    color: 'from-orange-500 to-red-600',
    features: ['GPS em tempo real', 'Cardápio móvel', 'Localização para clientes', 'Rota planejada'],
    techStack: ['React Native', 'Maps API', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '5-7 dias'
  },
  {
    id: 'local-delivery-network',
    name: 'Delivery Entre Lojas Locais',
    description: 'Rede de delivery colaborativo entre estabelecimentos',
    category: 'innovative',
    subcategory: 'Delivery',
    icon: Network,
    color: 'from-green-500 to-blue-600',
    features: ['Rede colaborativa', 'Compartilhamento de entregadores', 'Otimização de rotas', 'Comissões'],
    techStack: ['React', 'Maps API', 'Supabase', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '7-9 dias'
  },
  {
    id: 'pharmacy-drive-thru',
    name: 'Drive-thru para Farmácias',
    description: 'Sistema especializado para atendimento drive-thru',
    category: 'innovative',
    subcategory: 'Drive-thru',
    icon: Car,
    color: 'from-blue-500 to-cyan-600',
    features: ['Fila virtual', 'Pedido antecipado', 'Notificações', 'Pagamento sem contato'],
    techStack: ['React Native', 'Supabase', 'Push Notifications', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'coworking-scheduler',
    name: 'Agenda Compartilhada para Coworking',
    description: 'Sistema de reserva de espaços em coworking',
    category: 'innovative',
    subcategory: 'Coworking',
    icon: Users,
    color: 'from-purple-500 to-indigo-600',
    features: ['Reserva de salas', 'Pagamento por uso', 'Check-in digital', 'Recursos compartilhados'],
    techStack: ['React', 'Supabase', 'Calendar API', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-5 dias'
  },

  // Templates adicionais para completar
  {
    id: 'digital-loyalty-cards',
    name: 'Cartões Fidelidade Digital',
    description: 'Sistema digital de cartões fidelidade',
    category: 'other',
    subcategory: 'Fidelidade',
    icon: Star,
    color: 'from-yellow-500 to-orange-600',
    features: ['Cartões digitais', 'Pontuação automática', 'Recompensas', 'App mobile'],
    techStack: ['React Native', 'Supabase', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-4 dias'
  },
  {
    id: 'satisfaction-survey',
    name: 'Pesquisa de Satisfação QR Code',
    description: 'Pesquisas rápidas de satisfação via QR Code',
    category: 'other',
    subcategory: 'Pesquisa',
    icon: QrCode,
    color: 'from-blue-500 to-purple-600',
    features: ['QR Code por mesa/local', 'Respostas instantâneas', 'Analytics', 'NPS automático'],
    techStack: ['React', 'Supabase', 'QR Generator', 'Tailwind'],
    difficulty: 'beginner',
    estimatedTime: '2-3 dias'
  },
  {
    id: 'toy-rental-platform',
    name: 'Plataforma de Aluguel de Brinquedos',
    description: 'Sistema inovador para aluguel de brinquedos',
    category: 'other',
    subcategory: 'Aluguel',
    icon: Star,
    color: 'from-pink-500 to-purple-600',
    features: ['Catálogo por idade', 'Higienização controlada', 'Assinatura mensal', 'Troca ilimitada'],
    techStack: ['React', 'Supabase', 'Subscription APIs', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '4-6 dias'
  },
  {
    id: 'queue-management',
    name: 'Gerenciamento de Filas',
    description: 'Sistema digital de controle de filas',
    category: 'other',
    subcategory: 'Filas',
    icon: Users,
    color: 'from-green-500 to-emerald-600',
    features: ['Senha digital', 'Estimativa de tempo', 'Notificações', 'Painel digital'],
    techStack: ['React', 'Supabase', 'WebSocket', 'Tailwind'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 dias'
  },
  {
    id: 'franchise-management',
    name: 'Gestão de Franquias',
    description: 'Sistema unificado para gestão de franquias',
    category: 'other',
    subcategory: 'Franquias',
    icon: Building,
    color: 'from-blue-600 to-indigo-600',
    features: ['Relatórios globais', 'Padrões de marca', 'Performance por unidade', 'Treinamentos'],
    techStack: ['React', 'Supabase', 'Multi-tenant', 'Tailwind'],
    difficulty: 'advanced',
    estimatedTime: '8-10 dias'
  }
];

// Funções de busca e filtro
export const getTemplatesByCategory = (categoryId: string): ProjectTemplate[] => {
  if (categoryId === 'all') return projectTemplates;
  return projectTemplates.filter(template => template.category === categoryId);
};

export const searchTemplates = (searchTerm: string): ProjectTemplate[] => {
  const term = searchTerm.toLowerCase();
  return projectTemplates.filter(template => 
    template.name.toLowerCase().includes(term) ||
    template.description.toLowerCase().includes(term) ||
    template.tags.some(tag => tag.toLowerCase().includes(term)) ||
    template.features.some(feature => feature.toLowerCase().includes(term))
  );
};

export const getTemplateById = (id: string): ProjectTemplate | undefined => {
  return projectTemplates.find(template => template.id === id);
};

// Exportar aliases para compatibilidade
export const categories = templateCategories;
export { projectTemplates as templates };
