// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdmqmmxxwaqohlkcucwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbXFtbXh4d2Fxb2hsa2N1Y3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzgyODIsImV4cCI6MjA2NDQxNDI4Mn0.gAaxjogjOvuHjrWSK4xCdnCqi7-e8LA6I77QuHFFtzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);